// Generated by barrister - do not edit

using System.Collections.Generic;
using System.Text.Json.Serialization;
using Barrister2;

public enum OrderStatus
{
    pending,
    paid,
    shipped,
    delivered,
    cancelled
}

public enum PaymentMethod
{
    credit_card,
    debit_card,
    paypal,
    apple_pay
}


public class Product
{
    [JsonPropertyName("productId")]
    public required string ProductId { get; set; }

    [JsonPropertyName("name")]
    public required string Name { get; set; }

    [JsonPropertyName("description")]
    public required string Description { get; set; }

    [JsonPropertyName("price")]
    public required double Price { get; set; }

    [JsonPropertyName("stock")]
    public required int Stock { get; set; }

    [JsonPropertyName("imageUrl")]
    public string? ImageUrl { get; set; }

}

public class CartItem
{
    [JsonPropertyName("productId")]
    public required string ProductId { get; set; }

    [JsonPropertyName("quantity")]
    public required int Quantity { get; set; }

    [JsonPropertyName("price")]
    public required double Price { get; set; }

}

public class Cart
{
    [JsonPropertyName("cartId")]
    public required string CartId { get; set; }

    [JsonPropertyName("items")]
    public required List<CartItem> Items { get; set; }

    [JsonPropertyName("subtotal")]
    public required double Subtotal { get; set; }

}

public class Address
{
    [JsonPropertyName("street")]
    public required string Street { get; set; }

    [JsonPropertyName("city")]
    public required string City { get; set; }

    [JsonPropertyName("state")]
    public required string State { get; set; }

    [JsonPropertyName("zipCode")]
    public required string ZipCode { get; set; }

    [JsonPropertyName("country")]
    public required string Country { get; set; }

}

public class Order
{
    [JsonPropertyName("orderId")]
    public required string OrderId { get; set; }

    [JsonPropertyName("cart")]
    public required Cart Cart { get; set; }

    [JsonPropertyName("shippingAddress")]
    public required Address ShippingAddress { get; set; }

    [JsonPropertyName("paymentMethod")]
    public required PaymentMethod PaymentMethod { get; set; }

    [JsonPropertyName("status")]
    public required OrderStatus Status { get; set; }

    [JsonPropertyName("total")]
    public required double Total { get; set; }

    [JsonPropertyName("createdAt")]
    public required int CreatedAt { get; set; }

}

public class AddToCartRequest
{
    [JsonPropertyName("cartId")]
    public string? CartId { get; set; }

    [JsonPropertyName("productId")]
    public required string ProductId { get; set; }

    [JsonPropertyName("quantity")]
    public required int Quantity { get; set; }

}

public class CreateOrderRequest
{
    [JsonPropertyName("cartId")]
    public required string CartId { get; set; }

    [JsonPropertyName("shippingAddress")]
    public required Address ShippingAddress { get; set; }

    [JsonPropertyName("paymentMethod")]
    public required PaymentMethod PaymentMethod { get; set; }

}

public class CheckoutResponse
{
    [JsonPropertyName("orderId")]
    public required string OrderId { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

}


// IDL-specific type definitions for namespace: checkout
public static class checkoutIdl
{
    public static readonly Dictionary<string, Dictionary<string, object>> ALL_STRUCTS = new Dictionary<string, Dictionary<string, object>>
    {
        { "Product", new Dictionary<string, object>
        {
            { "fields", new List<Dictionary<string, object>>
            {
                new Dictionary<string, object>
                {
                    { "name", "productId" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "name" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "description" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "price" },
                    { "type", new Dictionary<string, object> { { "builtIn", "float" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "stock" },
                    { "type", new Dictionary<string, object> { { "builtIn", "int" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "imageUrl" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                    { "optional", true },
                },
            }},
        }},
        { "CartItem", new Dictionary<string, object>
        {
            { "fields", new List<Dictionary<string, object>>
            {
                new Dictionary<string, object>
                {
                    { "name", "productId" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "quantity" },
                    { "type", new Dictionary<string, object> { { "builtIn", "int" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "price" },
                    { "type", new Dictionary<string, object> { { "builtIn", "float" } } },
                },
            }},
        }},
        { "Cart", new Dictionary<string, object>
        {
            { "fields", new List<Dictionary<string, object>>
            {
                new Dictionary<string, object>
                {
                    { "name", "cartId" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "items" },
                    { "type", new Dictionary<string, object> { { "array", new Dictionary<string, object> { { "userDefined", "CartItem" } } } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "subtotal" },
                    { "type", new Dictionary<string, object> { { "builtIn", "float" } } },
                },
            }},
        }},
        { "Address", new Dictionary<string, object>
        {
            { "fields", new List<Dictionary<string, object>>
            {
                new Dictionary<string, object>
                {
                    { "name", "street" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "city" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "state" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "zipCode" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "country" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
            }},
        }},
        { "Order", new Dictionary<string, object>
        {
            { "fields", new List<Dictionary<string, object>>
            {
                new Dictionary<string, object>
                {
                    { "name", "orderId" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "cart" },
                    { "type", new Dictionary<string, object> { { "userDefined", "Cart" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "shippingAddress" },
                    { "type", new Dictionary<string, object> { { "userDefined", "Address" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "paymentMethod" },
                    { "type", new Dictionary<string, object> { { "userDefined", "PaymentMethod" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "status" },
                    { "type", new Dictionary<string, object> { { "userDefined", "OrderStatus" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "total" },
                    { "type", new Dictionary<string, object> { { "builtIn", "float" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "createdAt" },
                    { "type", new Dictionary<string, object> { { "builtIn", "int" } } },
                },
            }},
        }},
        { "AddToCartRequest", new Dictionary<string, object>
        {
            { "fields", new List<Dictionary<string, object>>
            {
                new Dictionary<string, object>
                {
                    { "name", "cartId" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                    { "optional", true },
                },
                new Dictionary<string, object>
                {
                    { "name", "productId" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "quantity" },
                    { "type", new Dictionary<string, object> { { "builtIn", "int" } } },
                },
            }},
        }},
        { "CreateOrderRequest", new Dictionary<string, object>
        {
            { "fields", new List<Dictionary<string, object>>
            {
                new Dictionary<string, object>
                {
                    { "name", "cartId" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "shippingAddress" },
                    { "type", new Dictionary<string, object> { { "userDefined", "Address" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "paymentMethod" },
                    { "type", new Dictionary<string, object> { { "userDefined", "PaymentMethod" } } },
                },
            }},
        }},
        { "CheckoutResponse", new Dictionary<string, object>
        {
            { "fields", new List<Dictionary<string, object>>
            {
                new Dictionary<string, object>
                {
                    { "name", "orderId" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                },
                new Dictionary<string, object>
                {
                    { "name", "message" },
                    { "type", new Dictionary<string, object> { { "builtIn", "string" } } },
                    { "optional", true },
                },
            }},
        }},
    };

    public static readonly Dictionary<string, Dictionary<string, object>> ALL_ENUMS = new Dictionary<string, Dictionary<string, object>>
    {
        { "OrderStatus", new Dictionary<string, object>
        {
            { "values", new List<Dictionary<string, object>>
            {
                new Dictionary<string, object>
                {
                    { "name", "pending" },
                },
                new Dictionary<string, object>
                {
                    { "name", "paid" },
                },
                new Dictionary<string, object>
                {
                    { "name", "shipped" },
                },
                new Dictionary<string, object>
                {
                    { "name", "delivered" },
                },
                new Dictionary<string, object>
                {
                    { "name", "cancelled" },
                },
            }},
        }},
        { "PaymentMethod", new Dictionary<string, object>
        {
            { "values", new List<Dictionary<string, object>>
            {
                new Dictionary<string, object>
                {
                    { "name", "credit_card" },
                },
                new Dictionary<string, object>
                {
                    { "name", "debit_card" },
                },
                new Dictionary<string, object>
                {
                    { "name", "paypal" },
                },
                new Dictionary<string, object>
                {
                    { "name", "apple_pay" },
                },
            }},
        }},
    };
}
