// Generated by barrister - do not edit
// Test server implementation for integration testing

using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;

public class CatalogServiceImpl : CatalogService
{
    public override List<Product> listProducts()
    {
        return new List<Product>();
    }

    public override Product? getProduct(string productId)
    {
        return null;
    }

}

public class CartServiceImpl : CartService
{
    public override Cart addToCart(AddToCartRequest request)
    {
        return new Cart
        {
            CartId = "test",
            Items = new List<CartItem>(),
            Subtotal = 3.14,
        };
    }

    public override Cart? getCart(string cartId)
    {
        return null;
    }

    public override bool clearCart(string cartId)
    {
        return true;
    }

}

public class OrderServiceImpl : OrderService
{
    public override CheckoutResponse createOrder(CreateOrderRequest request)
    {
        return new CheckoutResponse
        {
            OrderId = "test",
        };
    }

    public override Order? getOrder(string orderId)
    {
        return null;
    }

}

public class Program
{
    public static async Task Main(string[] args)
    {
        // Configure logging
        using var loggerFactory = LoggerFactory.Create(builder =>
        {
            builder.AddConsole().SetMinimumLevel(LogLevel.Debug);
        });
        var logger = loggerFactory.CreateLogger<BarristerServer>();

        var server = new BarristerServer(logger);
        server.Register("CatalogService", new CatalogServiceImpl());
        server.Register("CartService", new CartServiceImpl());
        server.Register("OrderService", new OrderServiceImpl());
        await server.RunAsync("0.0.0.0", 8080);
    }
}
