// Generated by barrister - do not edit
// Test client program for integration testing

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

public class Program
{
    public static async Task Main(string[] args)
    {
        var baseUrl = args.Length > 0 ? args[0] : "http://localhost:8080";
        var transport = new HttpTransport(baseUrl);
        var errors = new List<string>();

        var catalogserviceClient = new CatalogServiceClient(transport);

        try
        {
            var result = await catalogserviceClient.listProductsAsync();
            Console.WriteLine($"✓ CatalogService.listProducts passed");
        }
        catch (Exception e)
        {
            errors.Add($"CatalogService.listProducts failed: {e.Message}");
        }

        try
        {
            var result = await catalogserviceClient.getProductAsync("testproductId");
            Console.WriteLine($"✓ CatalogService.getProduct passed");
        }
        catch (Exception e)
        {
            errors.Add($"CatalogService.getProduct failed: {e.Message}");
        }

        var cartserviceClient = new CartServiceClient(transport);

        try
        {
            var result = await cartserviceClient.addToCartAsync(new AddToCartRequest
        {
            ProductId = "test",
            Quantity = 42
        });
            Console.WriteLine($"✓ CartService.addToCart passed");
        }
        catch (Exception e)
        {
            errors.Add($"CartService.addToCart failed: {e.Message}");
        }

        try
        {
            var result = await cartserviceClient.getCartAsync("testcartId");
            Console.WriteLine($"✓ CartService.getCart passed");
        }
        catch (Exception e)
        {
            errors.Add($"CartService.getCart failed: {e.Message}");
        }

        try
        {
            var result = await cartserviceClient.clearCartAsync("testcartId");
            Console.WriteLine($"✓ CartService.clearCart passed");
        }
        catch (Exception e)
        {
            errors.Add($"CartService.clearCart failed: {e.Message}");
        }

        var orderserviceClient = new OrderServiceClient(transport);

        try
        {
            var result = await orderserviceClient.createOrderAsync(new CreateOrderRequest
        {
            CartId = "test",
            ShippingAddress = new Address
        {
            Street = "test",
            City = "test",
            State = "test",
            ZipCode = "test",
            Country = "test"
        },
            PaymentMethod = PaymentMethod.credit_card
        });
            Console.WriteLine($"✓ OrderService.createOrder passed");
        }
        catch (Exception e)
        {
            errors.Add($"OrderService.createOrder failed: {e.Message}");
        }

        try
        {
            var result = await orderserviceClient.getOrderAsync("testorderId");
            Console.WriteLine($"✓ OrderService.getOrder passed");
        }
        catch (Exception e)
        {
            errors.Add($"OrderService.getOrder failed: {e.Message}");
        }

        if (errors.Count > 0)
        {
            Console.WriteLine($"FAILED: {errors.Count} test(s) failed");
            foreach (var error in errors)
            {
                Console.WriteLine($"  {error}");
            }
            Environment.Exit(1);
        }
        else
        {
            Console.WriteLine("SUCCESS: All tests passed!");
            Environment.Exit(0);
        }
    }
}
