// Generated by barrister - do not edit
// Test server implementation for integration testing

using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;

public class CatalogServiceImpl : CatalogService
{
    public override List<Product> listProducts()
    {
        // Return a valid list with a sample product to pass validation
        return new List<Product>
        {
            new Product
            {
                ProductId = "prod-1",
                Name = "Test Product",
                Description = "A test product",
                Price = 9.99,
                Stock = 100
            }
        };
    }

    public override Product? getProduct(string productId)
    {
        // Return a valid product to pass validation
        return new Product
        {
            ProductId = productId,
            Name = "Test Product",
            Description = "A test product",
            Price = 9.99,
            Stock = 100
        };
    }

}

public class CartServiceImpl : CartService
{
    public override Cart addToCart(AddToCartRequest request)
    {
        // Return a valid cart with items to pass validation
        return new Cart
        {
            CartId = "cart-1",
            Items = new List<CartItem>
            {
                new CartItem
                {
                    ProductId = request.ProductId,
                    Quantity = request.Quantity
                }
            }
        };
    }

    public override Cart? getCart(string cartId)
    {
        // Return a valid cart to pass validation
        return new Cart
        {
            CartId = cartId,
            Items = new List<CartItem>()
        };
    }

    public override bool clearCart(string cartId)
    {
        return true;
    }

}

public class OrderServiceImpl : OrderService
{
    public override CheckoutResponse createOrder(CreateOrderRequest request)
    {
        // Return a valid checkout response to pass validation
        return new CheckoutResponse
        {
            OrderId = "order-1",
            Status = "pending"
        };
    }

    public override Order? getOrder(string orderId)
    {
        // Return a valid order to pass validation
        return new Order
        {
            OrderId = orderId,
            Status = "pending",
            PaymentMethod = "credit_card",
            ShippingAddress = new Address
            {
                Street = "123 Test St",
                City = "Test City",
                State = "TS",
                ZipCode = "12345",
                Country = "USA"
            }
        };
    }

}

public class Program
{
    public static async Task Main(string[] args)
    {
        // Configure logging
        using var loggerFactory = LoggerFactory.Create(builder =>
        {
            builder.AddConsole().SetMinimumLevel(LogLevel.Information);
        });
        var logger = loggerFactory.CreateLogger<BarristerServer>();

        var server = new BarristerServer(logger);
        server.Register("CatalogService", new CatalogServiceImpl());
        server.Register("CartService", new CartServiceImpl());
        server.Register("OrderService", new OrderServiceImpl());
        await server.RunAsync("0.0.0.0", 8080);
    }
}
