// Generated by barrister - do not edit

package com.example.myapp.checkout;

import com.fasterxml.jackson.annotation.JsonProperty;
public class AddToCartRequest {
    @JsonProperty("cartId")
    private String cartId;

    @JsonProperty("productId")
    private String productId;

    @JsonProperty("quantity")
    private int quantity;

    public String getCartId() {
        return cartId;
    }

    public void setCartId(String cartId) {
        this.cartId = cartId;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

}
