// Generated by barrister - do not edit

package com.example.myapp.checkout;

import com.fasterxml.jackson.annotation.JsonProperty;
public class Cart {
    @JsonProperty("cartId")
    private String cartId;

    @JsonProperty("items")
    private java.util.List<CartItem> items;

    @JsonProperty("subtotal")
    private double subtotal;

    public String getCartId() {
        return cartId;
    }

    public void setCartId(String cartId) {
        this.cartId = cartId;
    }

    public java.util.List<CartItem> getItems() {
        return items;
    }

    public void setItems(java.util.List<CartItem> items) {
        this.items = items;
    }

    public double getSubtotal() {
        return subtotal;
    }

    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }

}
