// Generated by barrister - do not edit

package com.example.myapp.checkout;

import com.bitmechanic.barrister2.*;
import com.fasterxml.jackson.core.type.TypeReference;
public class CartServiceClient implements CartService {
    private final Transport transport;
    private final JsonParser jsonParser;

    public CartServiceClient(Transport transport, JsonParser jsonParser) {
        this.transport = transport;
        this.jsonParser = jsonParser;
    }

    @Override
    public Cart addToCart(AddToCartRequest request) {
        try {
            String method = "CartService.addToCart";
            Object[] params = new Object[] { request };

            Request rpcRequest = new Request(method, params, java.util.UUID.randomUUID().toString());
            Response response = transport.call(rpcRequest);

            if (response.getResult() == null) {
                throw new RPCError(-32603, "Internal error", "Missing result in response");
            }

            String resultJson = jsonParser.toJson(response.getResult());
            com.fasterxml.jackson.core.type.TypeReference<Cart> typeRef = new com.fasterxml.jackson.core.type.TypeReference<Cart>() {};
            return jsonParser.fromJson(resultJson, typeRef.getType());
        } catch (Exception e) {
            if (e instanceof RPCError) {
                throw (RPCError) e;
            }
            throw new RPCError(-32603, "Internal error", e.getMessage());
        }
    }

    @Override
    public Cart getCart(String cartId) {
        try {
            String method = "CartService.getCart";
            Object[] params = new Object[] { cartId };

            Request rpcRequest = new Request(method, params, java.util.UUID.randomUUID().toString());
            Response response = transport.call(rpcRequest);

            if (response.getResult() == null) {
                return null;
            }

            String resultJson = jsonParser.toJson(response.getResult());
            com.fasterxml.jackson.core.type.TypeReference<Cart> typeRef = new com.fasterxml.jackson.core.type.TypeReference<Cart>() {};
            return jsonParser.fromJson(resultJson, typeRef.getType());
        } catch (Exception e) {
            if (e instanceof RPCError) {
                throw (RPCError) e;
            }
            throw new RPCError(-32603, "Internal error", e.getMessage());
        }
    }

    @Override
    public boolean clearCart(String cartId) {
        try {
            String method = "CartService.clearCart";
            Object[] params = new Object[] { cartId };

            Request rpcRequest = new Request(method, params, java.util.UUID.randomUUID().toString());
            Response response = transport.call(rpcRequest);

            if (response.getResult() == null) {
                throw new RPCError(-32603, "Internal error", "Missing result in response");
            }

            String resultJson = jsonParser.toJson(response.getResult());
            com.fasterxml.jackson.core.type.TypeReference<Boolean> typeRef = new com.fasterxml.jackson.core.type.TypeReference<Boolean>() {};
            return jsonParser.fromJson(resultJson, typeRef.getType());
        } catch (Exception e) {
            if (e instanceof RPCError) {
                throw (RPCError) e;
            }
            throw new RPCError(-32603, "Internal error", e.getMessage());
        }
    }

}
