// Generated by barrister - do not edit

package com.example.myapp.checkout;

public interface CartService {
    public Cart addToCart(AddToCartRequest request);

    public Cart getCart(String cartId);

    public boolean clearCart(String cartId);

}
