// Generated by barrister - do not edit

package com.example.myapp.checkout;

public class OrderServiceImpl implements OrderService {
    @Override
    public CheckoutResponse createOrder(CreateOrderRequest request) {
        return null;
    }

    @Override
    public Order getOrder(String orderId) {
        return null;
    }

}
