// Generated by barrister - do not edit

package com.example.myapp.checkout;

public interface OrderService {
    public CheckoutResponse createOrder(CreateOrderRequest request);

    public Order getOrder(String orderId);

}
