// Generated by barrister - do not edit

package com.example.myapp.checkout;

import com.bitmechanic.barrister2.*;
import com.fasterxml.jackson.core.type.TypeReference;
public class OrderServiceClient implements OrderService {
    private final Transport transport;
    private final JsonParser jsonParser;

    public OrderServiceClient(Transport transport, JsonParser jsonParser) {
        this.transport = transport;
        this.jsonParser = jsonParser;
    }

    @Override
    public CheckoutResponse createOrder(CreateOrderRequest request) {
        try {
            String method = "OrderService.createOrder";
            Object[] params = new Object[] { request };

            Request rpcRequest = new Request(method, params, java.util.UUID.randomUUID().toString());
            Response response = transport.call(rpcRequest);

            if (response.getResult() == null) {
                throw new RPCError(-32603, "Internal error", "Missing result in response");
            }

            String resultJson = jsonParser.toJson(response.getResult());
            com.fasterxml.jackson.core.type.TypeReference<CheckoutResponse> typeRef = new com.fasterxml.jackson.core.type.TypeReference<CheckoutResponse>() {};
            return jsonParser.fromJson(resultJson, typeRef.getType());
        } catch (Exception e) {
            if (e instanceof RPCError) {
                throw (RPCError) e;
            }
            throw new RPCError(-32603, "Internal error", e.getMessage());
        }
    }

    @Override
    public Order getOrder(String orderId) {
        try {
            String method = "OrderService.getOrder";
            Object[] params = new Object[] { orderId };

            Request rpcRequest = new Request(method, params, java.util.UUID.randomUUID().toString());
            Response response = transport.call(rpcRequest);

            if (response.getResult() == null) {
                return null;
            }

            String resultJson = jsonParser.toJson(response.getResult());
            com.fasterxml.jackson.core.type.TypeReference<Order> typeRef = new com.fasterxml.jackson.core.type.TypeReference<Order>() {};
            return jsonParser.fromJson(resultJson, typeRef.getType());
        } catch (Exception e) {
            if (e instanceof RPCError) {
                throw (RPCError) e;
            }
            throw new RPCError(-32603, "Internal error", e.getMessage());
        }
    }

}
