# Generated by barrister - do not edit

from barrister2 import (
    RPCError,
    validate_type,
    validate_struct,
    validate_enum,
    find_struct,
    find_enum,
    get_struct_fields,
)

# IDL-specific type definitions
ALL_STRUCTS = {
    'Book': {
        'fields': [
            {
                'name': 'productId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'dateCreated',
                'type': {'builtIn': 'int'},
            },
            {
                'name': 'dateUpdated',
                'type': {'builtIn': 'int'},
            },
            {
                'name': 'platform',
                'type': {'userDefined': 'Platform'},
            },
            {
                'name': 'author',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'title',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'productUrl',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'imageUrl',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'lendable',
                'type': {'builtIn': 'bool'},
            },
        ],
    },
    'BookWithStatus': {
        'extends': 'Book',
        'fields': [
            {
                'name': 'userStatus',
                'type': {'userDefined': 'BookUserStatus'},
            },
        ],
    },
    'BookWithScore': {
        'extends': 'BookWithStatus',
        'fields': [
            {
                'name': 'score',
                'type': {'builtIn': 'float'},
            },
        ],
    },
    'User': {
        'fields': [
            {
                'name': 'userId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'name',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'points',
                'type': {'builtIn': 'int'},
            },
            {
                'name': 'dateCreated',
                'type': {'builtIn': 'int'},
            },
            {
                'name': 'email',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'kindleEmail',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'nookEmail',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'emailOptIn',
                'type': {'builtIn': 'bool'},
            },
        ],
    },
    'UserUpdate': {
        'fields': [
            {
                'name': 'userId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'name',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'email',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'kindleEmail',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'nookEmail',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'emailOptIn',
                'type': {'builtIn': 'bool'},
            },
        ],
    },
    'SearchRequest': {
        'fields': [
            {
                'name': 'platforms',
                'type': {'array': {'userDefined': 'Platform'}},
            },
            {
                'name': 'userId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'keyword',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'offset',
                'type': {'builtIn': 'int'},
            },
            {
                'name': 'limit',
                'type': {'builtIn': 'int'},
            },
        ],
    },
    'Recipient': {
        'fields': [
            {
                'name': 'userId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'email',
                'type': {'builtIn': 'string'},
            },
        ],
    },
    'ToLoanTask': {
        'fields': [
            {
                'name': 'book',
                'type': {'userDefined': 'Book'},
            },
            {
                'name': 'recipients',
                'type': {'array': {'userDefined': 'Recipient'}},
            },
        ],
    },
    'ToAckTask': {
        'fields': [
            {
                'name': 'book',
                'type': {'userDefined': 'Book'},
            },
            {
                'name': 'fromEmail',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'loanId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'dateLoaned',
                'type': {'builtIn': 'int'},
            },
        ],
    },
    'BaseResponse': {
        'fields': [
            {
                'name': 'status',
                'type': {'userDefined': 'Status'},
            },
            {
                'name': 'message',
                'type': {'builtIn': 'string'},
            },
        ],
    },
    'UserResponse': {
        'extends': 'BaseResponse',
        'fields': [
            {
                'name': 'user',
                'type': {'userDefined': 'User'},
            },
        ],
    },
    'BookResponse': {
        'extends': 'BaseResponse',
        'fields': [
            {
                'name': 'userId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'book',
                'type': {'userDefined': 'BookWithStatus'},
            },
        ],
    },
    'BooksResponse': {
        'extends': 'BaseResponse',
        'fields': [
            {
                'name': 'userId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'totalRows',
                'type': {'builtIn': 'int'},
            },
            {
                'name': 'offset',
                'type': {'builtIn': 'int'},
            },
            {
                'name': 'books',
                'type': {'array': {'userDefined': 'BookWithStatus'}},
            },
        ],
    },
    'DeleteResponse': {
        'extends': 'BaseResponse',
        'fields': [
            {
                'name': 'deleteCount',
                'type': {'builtIn': 'int'},
            },
        ],
    },
    'RecommendationsResponse': {
        'extends': 'BaseResponse',
        'fields': [
            {
                'name': 'userId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'books',
                'type': {'array': {'userDefined': 'BookWithScore'}},
            },
        ],
    },
    'UserBooksResponse': {
        'extends': 'BaseResponse',
        'fields': [
            {
                'name': 'userId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'want',
                'type': {'array': {'userDefined': 'Book'}},
            },
            {
                'name': 'have',
                'type': {'array': {'userDefined': 'Book'}},
            },
            {
                'name': 'dislike',
                'type': {'array': {'userDefined': 'Book'}},
            },
        ],
    },
    'TasksResponse': {
        'extends': 'BaseResponse',
        'fields': [
            {
                'name': 'userId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'toLoan',
                'type': {'array': {'userDefined': 'ToLoanTask'}},
            },
            {
                'name': 'toAck',
                'type': {'array': {'userDefined': 'ToAckTask'}},
            },
        ],
    },
    'LoanResponse': {
        'extends': 'BaseResponse',
        'fields': [
            {
                'name': 'loanId',
                'type': {'builtIn': 'string'},
            },
        ],
    },
    'ActivityResponse': {
        'extends': 'BaseResponse',
        'fields': [
            {
                'name': 'activity',
                'type': {'array': {'userDefined': 'BookWithStatus'}},
            },
        ],
    },
}

ALL_ENUMS = {
    'Platform': {
        'values': [
            {'name': 'kindle'},
            {'name': 'nook'},
        ],
    },
    'BookUserStatus': {
        'values': [
            {'name': 'none'},
            {'name': 'want'},
            {'name': 'have'},
            {'name': 'dislike'},
        ],
    },
    'Status': {
        'values': [
            {'name': 'success'},
            {'name': 'fatal'},
            {'name': 'invalid'},
            {'name': 'notfound'},
            {'name': 'denied'},
        ],
    },
}
