// Generated by barrister - do not edit
// Test server implementation for integration testing

package main

import (
	"math"
	"strings"
)

type CatalogServiceImpl struct{}

func (i *CatalogServiceImpl) ListProducts() ([]Product, error) {
	var zero []Product
	return zero, nil
}

func (i *CatalogServiceImpl) GetProduct(productId string) (*Product, error) {
	var zero *Product
	return zero, nil
}

type CartServiceImpl struct{}

func (i *CartServiceImpl) AddToCart(request AddToCartRequest) (Cart, error) {
	var zero Cart
	return zero, nil
}

func (i *CartServiceImpl) GetCart(cartId string) (*Cart, error) {
	var zero *Cart
	return zero, nil
}

func (i *CartServiceImpl) ClearCart(cartId string) (bool, error) {
	var zero bool
	return zero, nil
}

type OrderServiceImpl struct{}

func (i *OrderServiceImpl) CreateOrder(request CreateOrderRequest) (CheckoutResponse, error) {
	var zero CheckoutResponse
	return zero, nil
}

func (i *OrderServiceImpl) GetOrder(orderId string) (*Order, error) {
	var zero *Order
	return zero, nil
}

func main() {
	server := NewBarristerServer("0.0.0.0", 8080)
	server.Register("CatalogService", &CatalogServiceImpl{})
	server.Register("CartService", &CartServiceImpl{})
	server.Register("OrderService", &OrderServiceImpl{})
	if err := server.ServeForever(); err != nil {
		panic(err)
	}
}
