// Generated by barrister - do not edit

package com.example.myapp;

import com.bitmechanic.barrister2.*;
import com.example.myapp.checkout.CatalogServiceImpl;
import com.example.myapp.checkout.CartServiceImpl;
import com.example.myapp.checkout.OrderServiceImpl;

public class TestServer extends Server {
    public TestServer(int port, JsonParser jsonParser) throws Exception {
        super(port, jsonParser);
    }

    public static void main(String[] args) {
        try {
            JsonParser jsonParser = new JacksonJsonParser();
            int port = 8080;
            if (args.length > 0) {
                port = Integer.parseInt(args[0]);
            }
            TestServer server = new TestServer(port, jsonParser);

            server.register("CatalogService", new com.example.myapp.checkout.CatalogServiceImpl());
            server.register("CartService", new com.example.myapp.checkout.CartServiceImpl());
            server.register("OrderService", new com.example.myapp.checkout.OrderServiceImpl());
            server.start();
            System.out.println("Test server started on port " + port);
            // Keep server running indefinitely
            Object lock = new Object();
            synchronized (lock) {
                lock.wait();
            }
        } catch (Exception e) {
            System.err.println("Fatal error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }
}
