// Generated by barrister - do not edit

import com.bitmechanic.barrister2.*;
import checkout.checkout.CatalogServiceClient;
import checkout.checkout.CartServiceClient;
import checkout.checkout.OrderServiceClient;

public class TestClient {
    public static void main(String[] args) throws Exception {
        JsonParser jsonParser = new JacksonJsonParser();
        String baseUrl = args.length > 0 ? args[0] : "http://localhost:8080";
        Transport transport = new HTTPTransport(baseUrl, jsonParser);

        checkout.checkout.CatalogServiceClient catalogserviceClient = new checkout.checkout.CatalogServiceClient(transport, jsonParser);
        try {
            var result = catalogserviceClient.listProducts();
            System.out.println("✓ CatalogService.listProducts passed");
        } catch (Exception e) {
            System.err.println("✗ CatalogService.listProducts failed: " + e.getMessage());
        }
        try {
            var result = catalogserviceClient.getProduct("testproductId");
            System.out.println("✓ CatalogService.getProduct passed");
        } catch (Exception e) {
            System.err.println("✗ CatalogService.getProduct failed: " + e.getMessage());
        }

        checkout.checkout.CartServiceClient cartserviceClient = new checkout.checkout.CartServiceClient(transport, jsonParser);
        try {
            var result = cartserviceClient.addToCart(null);
            System.out.println("✓ CartService.addToCart passed");
        } catch (Exception e) {
            System.err.println("✗ CartService.addToCart failed: " + e.getMessage());
        }
        try {
            var result = cartserviceClient.getCart("testcartId");
            System.out.println("✓ CartService.getCart passed");
        } catch (Exception e) {
            System.err.println("✗ CartService.getCart failed: " + e.getMessage());
        }
        try {
            var result = cartserviceClient.clearCart("testcartId");
            System.out.println("✓ CartService.clearCart passed");
        } catch (Exception e) {
            System.err.println("✗ CartService.clearCart failed: " + e.getMessage());
        }

        checkout.checkout.OrderServiceClient orderserviceClient = new checkout.checkout.OrderServiceClient(transport, jsonParser);
        try {
            var result = orderserviceClient.createOrder(null);
            System.out.println("✓ OrderService.createOrder passed");
        } catch (Exception e) {
            System.err.println("✗ OrderService.createOrder failed: " + e.getMessage());
        }
        try {
            var result = orderserviceClient.getOrder("testorderId");
            System.out.println("✓ OrderService.getOrder passed");
        } catch (Exception e) {
            System.err.println("✗ OrderService.getOrder failed: " + e.getMessage());
        }

        System.out.println("Test client completed");
    }
}
