// Generated by barrister - do not edit

import com.bitmechanic.barrister2.*;
import checkout.checkout.CatalogServiceImpl;
import checkout.checkout.CartServiceImpl;
import checkout.checkout.OrderServiceImpl;

public class TestServer extends Server {
    public TestServer(int port, JsonParser jsonParser) throws Exception {
        super(port, jsonParser);
    }

    public static void main(String[] args) {
        try {
            JsonParser jsonParser = new JacksonJsonParser();
            TestServer server = new TestServer(8080, jsonParser);

            server.register("CatalogService", new checkout.checkout.CatalogServiceImpl());
            server.register("CartService", new checkout.checkout.CartServiceImpl());
            server.register("OrderService", new checkout.checkout.OrderServiceImpl());
            server.start();
            System.out.println("Test server started on port 8080");
            // Keep server running indefinitely
            Object lock = new Object();
            synchronized (lock) {
                lock.wait();
            }
        } catch (Exception e) {
            System.err.println("Fatal error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }
}
