// Generated by barrister - do not edit

package com.example.myapp;

import com.bitmechanic.barrister2.*;
import java.io.*;
import java.net.*;
import java.net.http.*;
import java.net.http.HttpRequest.*;
import java.net.http.HttpResponse.*;
import java.util.*;
import java.util.concurrent.*;

public class Client {
    private final HttpClient httpClient;
    private final String baseUrl;
    private final JsonParser jsonParser;
    private final Map<String, Map<String, Object>> allStructs;
    private final Map<String, Map<String, Object>> allEnums;

    public Client(String baseUrl, JsonParser jsonParser) {
        this.httpClient = HttpClient.newHttpClient();
        this.baseUrl = baseUrl;
        this.jsonParser = jsonParser;
        this.allStructs = new HashMap<>();
        this.allEnums = new HashMap<>();

        this.allStructs.putAll(com.example.myapp.checkout.checkoutIdl.ALL_STRUCTS);
        this.allEnums.putAll(com.example.myapp.checkout.checkoutIdl.ALL_ENUMS);
    }

    @SuppressWarnings("unchecked")
    public Map<String, Object> call(String method, Map<String, Object> params) throws Exception {
        Map<String, Object> request = Map.of(
            "jsonrpc", "2.0",
            "method", method,
            "params", params,
            "id", 1
        );

        String requestBody = jsonParser.toJson(request);

        HttpRequest httpRequest = HttpRequest.newBuilder()
            .uri(URI.create(baseUrl))
            .header("Content-Type", "application/json")
            .POST(HttpRequest.BodyPublishers.ofString(requestBody))
            .build();

        HttpResponse<String> response = httpClient.send(httpRequest, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new RuntimeException("HTTP error: " + response.statusCode());
        }

        Map<String, Object> jsonResponse = jsonParser.fromJson(response.body(), Map.class);

        if (jsonResponse.containsKey("error")) {
            Map<String, Object> error = (Map<String, Object>) jsonResponse.get("error");
            throw new RPCError(
                ((Number) error.get("code")).intValue(),
                (String) error.get("message"),
                error.get("data")
            );
        }

        return (Map<String, Object>) jsonResponse.get("result");
    }
}
