// Generated by barrister - do not edit

// Type definitions (TypeScript types, erased at runtime)
interface TypeDef {
  builtIn?: string;
  array?: TypeDef;
  mapValue?: TypeDef;
  userDefined?: string;
}
interface StructDef {
  extends?: string;
  fields: Array<{ name: string; type: TypeDef; optional?: boolean }>;
}
interface EnumDef {
  values: Array<{ name: string }>;
}
type StructMap = { [key: string]: StructDef };
type EnumMap = { [key: string]: EnumDef };

// IDL-specific type definitions for namespace: checkout
const ALL_STRUCTS: StructMap = {
  'Product': {
    fields: [
      {
        name: 'productId',
        type: {builtIn: 'string'},
      },
      {
        name: 'name',
        type: {builtIn: 'string'},
      },
      {
        name: 'description',
        type: {builtIn: 'string'},
      },
      {
        name: 'price',
        type: {builtIn: 'float'},
      },
      {
        name: 'stock',
        type: {builtIn: 'int'},
      },
      {
        name: 'imageUrl',
        type: {builtIn: 'string'},
        optional: true,
      },
    ],
  },
  'CartItem': {
    fields: [
      {
        name: 'productId',
        type: {builtIn: 'string'},
      },
      {
        name: 'quantity',
        type: {builtIn: 'int'},
      },
      {
        name: 'price',
        type: {builtIn: 'float'},
      },
    ],
  },
  'Cart': {
    fields: [
      {
        name: 'cartId',
        type: {builtIn: 'string'},
      },
      {
        name: 'items',
        type: {array: {userDefined: 'CartItem'}},
      },
      {
        name: 'subtotal',
        type: {builtIn: 'float'},
      },
    ],
  },
  'Address': {
    fields: [
      {
        name: 'street',
        type: {builtIn: 'string'},
      },
      {
        name: 'city',
        type: {builtIn: 'string'},
      },
      {
        name: 'state',
        type: {builtIn: 'string'},
      },
      {
        name: 'zipCode',
        type: {builtIn: 'string'},
      },
      {
        name: 'country',
        type: {builtIn: 'string'},
      },
    ],
  },
  'Order': {
    fields: [
      {
        name: 'orderId',
        type: {builtIn: 'string'},
      },
      {
        name: 'cart',
        type: {userDefined: 'Cart'},
      },
      {
        name: 'shippingAddress',
        type: {userDefined: 'Address'},
      },
      {
        name: 'paymentMethod',
        type: {userDefined: 'PaymentMethod'},
      },
      {
        name: 'status',
        type: {userDefined: 'OrderStatus'},
      },
      {
        name: 'total',
        type: {builtIn: 'float'},
      },
      {
        name: 'createdAt',
        type: {builtIn: 'int'},
      },
    ],
  },
  'AddToCartRequest': {
    fields: [
      {
        name: 'cartId',
        type: {builtIn: 'string'},
        optional: true,
      },
      {
        name: 'productId',
        type: {builtIn: 'string'},
      },
      {
        name: 'quantity',
        type: {builtIn: 'int'},
      },
    ],
  },
  'CreateOrderRequest': {
    fields: [
      {
        name: 'cartId',
        type: {builtIn: 'string'},
      },
      {
        name: 'shippingAddress',
        type: {userDefined: 'Address'},
      },
      {
        name: 'paymentMethod',
        type: {userDefined: 'PaymentMethod'},
      },
    ],
  },
  'CheckoutResponse': {
    fields: [
      {
        name: 'orderId',
        type: {builtIn: 'string'},
      },
      {
        name: 'message',
        type: {builtIn: 'string'},
        optional: true,
      },
    ],
  },
};

const ALL_ENUMS: EnumMap = {
  'OrderStatus': {
    values: [
      { name: 'pending' },
      { name: 'paid' },
      { name: 'shipped' },
      { name: 'delivered' },
      { name: 'cancelled' },
    ],
  },
  'PaymentMethod': {
    values: [
      { name: 'credit_card' },
      { name: 'debit_card' },
      { name: 'paypal' },
      { name: 'apple_pay' },
    ],
  },
};

// Export for CommonJS compatibility
export { ALL_STRUCTS, ALL_ENUMS };
