// Generated by barrister - do not edit
// Test client for integration testing

/// <reference types="node" />

import { HTTPTransport, CatalogServiceClient, CartServiceClient, OrderServiceClient } from './client';
import * as http from 'http';

async function waitForServer(url: string, timeout: number = 10000): Promise<boolean> {
  const startTime = Date.now();
  let retryDelay = 200; // Start with 200ms delay, will increase exponentially

  while (Date.now() - startTime < timeout) {
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 2000);

      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: '{"jsonrpc":"2.0","method":"barrister-idl","id":1}',
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      // Accept 2xx status codes as success
      if (response.ok) {
        return true;
      } else {
        // Server responded but with error status - fail fast
        console.error(`Server responded with status ${response.status}`);
        return false;
      }
    } catch (err: any) {
      // Check if this is a network/connection error (retry) or abort (stop)
      if (err.name === 'AbortError') {
        console.error('Request timed out, server may not be ready');
      } else if (err.code === 'ECONNREFUSED' || err.code === 'ENOTFOUND') {
        // Connection refused or host not found - server not ready yet
      } else {
        // Other errors - log and continue trying
        console.error(`Connection error: ${err.message}`);
      }
    }

    // Wait before retrying with exponential backoff
    await new Promise(resolve => setTimeout(resolve, retryDelay));
    retryDelay = Math.min(retryDelay * 1.5, 1000); // Cap at 1 second
  }

  return false;
}

async function main() {
  const serverUrl = 'http://localhost:8080';

  // Wait for server to be ready (shell script already waited, but do a final check)
  if (!(await waitForServer(serverUrl, 10000))) {
    console.error('ERROR: Server did not become ready in time');
    process.exit(1);
  }

  console.log('Server is ready. Running tests...');
  console.log();

  // Create transport and clients
  const transport = new HTTPTransport(serverUrl);
  const catalogserviceClient = new CatalogServiceClient(transport);
  const cartserviceClient = new CartServiceClient(transport);
  const orderserviceClient = new OrderServiceClient(transport);

  const errors: string[] = [];

  // Test CatalogService.listProducts
  try {
    const result = await catalogserviceClient.listProducts();
    if (result === null || result === undefined) {
      throw new Error('Expected non-null result');
    }
    console.log('✓ CatalogService.listProducts passed');
  } catch (err: any) {
    const errorMsg = `CatalogService.listProducts failed: ${err.message || err}`;
    errors.push(errorMsg);
    console.error(`✗ ${errorMsg}`);
  }

  // Test CatalogService.getProduct
  try {
    const result = await catalogserviceClient.getProduct('test');
    if (result === null || result === undefined) {
      throw new Error('Expected non-null result');
    }
    console.log('✓ CatalogService.getProduct passed');
  } catch (err: any) {
    const errorMsg = `CatalogService.getProduct failed: ${err.message || err}`;
    errors.push(errorMsg);
    console.error(`✗ ${errorMsg}`);
  }

  // Test CartService.addToCart
  try {
    const result = await cartserviceClient.addToCart({ productId: 'test', quantity: 1 });
    if (result === null || result === undefined) {
      throw new Error('Expected non-null result');
    }
    console.log('✓ CartService.addToCart passed');
  } catch (err: any) {
    const errorMsg = `CartService.addToCart failed: ${err.message || err}`;
    errors.push(errorMsg);
    console.error(`✗ ${errorMsg}`);
  }

  // Test CartService.getCart
  try {
    const result = await cartserviceClient.getCart('test');
    if (result === null || result === undefined) {
      throw new Error('Expected non-null result');
    }
    console.log('✓ CartService.getCart passed');
  } catch (err: any) {
    const errorMsg = `CartService.getCart failed: ${err.message || err}`;
    errors.push(errorMsg);
    console.error(`✗ ${errorMsg}`);
  }

  // Test CartService.clearCart
  try {
    const result = await cartserviceClient.clearCart('test');
    if (result === null || result === undefined) {
      throw new Error('Expected non-null result');
    }
    console.log('✓ CartService.clearCart passed');
  } catch (err: any) {
    const errorMsg = `CartService.clearCart failed: ${err.message || err}`;
    errors.push(errorMsg);
    console.error(`✗ ${errorMsg}`);
  }

  // Test OrderService.createOrder
  try {
    const result = await orderserviceClient.createOrder({ cartId: 'test', shippingAddress: { street: 'test', city: 'test', state: 'test', zipCode: 'test', country: 'test' }, paymentMethod: 'credit_card' });
    if (result === null || result === undefined) {
      throw new Error('Expected non-null result');
    }
    console.log('✓ OrderService.createOrder passed');
  } catch (err: any) {
    const errorMsg = `OrderService.createOrder failed: ${err.message || err}`;
    errors.push(errorMsg);
    console.error(`✗ ${errorMsg}`);
  }

  // Test OrderService.getOrder
  try {
    const result = await orderserviceClient.getOrder('test');
    if (result === null || result === undefined) {
      throw new Error('Expected non-null result');
    }
    console.log('✓ OrderService.getOrder passed');
  } catch (err: any) {
    const errorMsg = `OrderService.getOrder failed: ${err.message || err}`;
    errors.push(errorMsg);
    console.error(`✗ ${errorMsg}`);
  }

  // Report results
  console.log();
  if (errors.length > 0) {
    console.error(`FAILED: ${errors.length} test(s) failed:`);
    for (const error of errors) {
      console.error(`  - ${error}`);
    }
    process.exit(1);
  } else {
    console.log('SUCCESS: All tests passed!');
    process.exit(0);
  }
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
