// Generated by barrister - do not edit
// Test server implementation for integration testing

import { BarristerServer, CatalogService, CartService, OrderService } from './server';

class CatalogServiceImpl extends CatalogService {
  // Test implementation of CatalogService interface

  listProducts(): any {
    // Return a valid list with a sample product to pass validation
    return [{
      productId: 'prod-1',
      name: 'Test Product',
      description: 'A test product',
      price: 9.99,
      stock: 100,
    }];
  }

  getProduct(productId: any): any {
    // Return a valid product to pass validation
    return {
      productId: productId,
      name: 'Test Product',
      description: 'A test product',
      price: 9.99,
      stock: 100,
    };
  }

}

class CartServiceImpl extends CartService {
  // Test implementation of CartService interface

  addToCart(request: any): any {
    // Return a valid cart with items to pass validation
    return {
      cartId: 'cart-1',
      items: [{
        productId: request.productId,
        quantity: request.quantity,
      }],
      subtotal: 0.0,
    };
  }

  getCart(cartId: any): any {
    // Return a valid cart to pass validation
    return {
      cartId: cartId,
      items: [],
      subtotal: 0.0,
    };
  }

  clearCart(cartId: any): any {
    return true;
  }

}

class OrderServiceImpl extends OrderService {
  // Test implementation of OrderService interface

  createOrder(request: any): any {
    // Return a valid checkout response to pass validation
    return {
      orderId: 'order-1',
    };
  }

  getOrder(orderId: any): any {
    // Return a valid order to pass validation
    return {
      orderId: orderId,
      cart: {
        cartId: 'cart-1',
        items: [],
        subtotal: 0.0,
      },
      shippingAddress: {
        street: '123 Test St',
        city: 'Test City',
        state: 'TS',
        zipCode: '12345',
        country: 'USA',
      },
      paymentMethod: 'credit_card',
      status: 'pending',
      total: 0.0,
      createdAt: 0,
    };
  }

}

// Main entry point
const server = new BarristerServer('0.0.0.0', 8080);
server.register('CatalogService', new CatalogServiceImpl());
server.register('CartService', new CartServiceImpl());
server.register('OrderService', new OrderServiceImpl());
server.serveForever();
