// Generated by barrister - do not edit
// Test client for integration testing

package main

import (
	"bytes"
	"fmt"
	"net/http"
	"os"
	"time"
)

func waitForServer(url string, timeout time.Duration) bool {
	start := time.Now()
	for time.Since(start) < timeout {
		resp, err := http.Post(url, "application/json", bytes.NewReader([]byte("{\"jsonrpc\":\"2.0\",\"method\":\"barrister-idl\",\"id\":1}")))
		if err == nil && resp.StatusCode == 200 {
			resp.Body.Close()
			return true
		}
		if resp != nil {
			resp.Body.Close()
		}
		time.Sleep(500 * time.Millisecond)
	}
	return false
}

func main() {
	serverURL := "http://localhost:8080"
	if len(os.Args) > 1 {
		serverURL = os.Args[1]
	}

	fmt.Println("Waiting for server to be ready...")
	if !waitForServer(serverURL, 10*time.Second) {
		fmt.Fprintf(os.Stderr, "ERROR: Server did not become ready in time\n")
		os.Exit(1)
	}

	fmt.Println("Server is ready. Running tests...")
	fmt.Println()

	transport := NewHTTPTransport(serverURL, nil)
	catalogserviceClient := NewCatalogServiceClient(transport)
	cartserviceClient := NewCartServiceClient(transport)
	orderserviceClient := NewOrderServiceClient(transport)

	errors := []string{}

	// Test CatalogService.listProducts
	func() {
		defer func() {
			if r := recover(); r != nil {
				errors = append(errors, fmt.Sprintf("CatalogService.listProducts failed: %v", r))
			}
		}()
		result, err := catalogserviceClient.ListProducts()
		if err != nil {
			errors = append(errors, fmt.Sprintf("CatalogService.listProducts failed: %v", err))
			return
		}
		_ = result // Use result to avoid unused variable
		fmt.Printf("✓ CatalogService.listProducts passed\n")
	}()

	// Test CatalogService.getProduct
	func() {
		defer func() {
			if r := recover(); r != nil {
				errors = append(errors, fmt.Sprintf("CatalogService.getProduct failed: %v", r))
			}
		}()
		result, err := catalogserviceClient.GetProduct("test")
		if err != nil {
			errors = append(errors, fmt.Sprintf("CatalogService.getProduct failed: %v", err))
			return
		}
		_ = result // Use result to avoid unused variable
		fmt.Printf("✓ CatalogService.getProduct passed\n")
	}()

	// Test CartService.addToCart
	func() {
		defer func() {
			if r := recover(); r != nil {
				errors = append(errors, fmt.Sprintf("CartService.addToCart failed: %v", r))
			}
		}()
		result, err := cartserviceClient.AddToCart(AddToCartRequest{ProductId: "test", Quantity: 1})
		if err != nil {
			errors = append(errors, fmt.Sprintf("CartService.addToCart failed: %v", err))
			return
		}
		_ = result // Use result to avoid unused variable
		fmt.Printf("✓ CartService.addToCart passed\n")
	}()

	// Test CartService.getCart
	func() {
		defer func() {
			if r := recover(); r != nil {
				errors = append(errors, fmt.Sprintf("CartService.getCart failed: %v", r))
			}
		}()
		result, err := cartserviceClient.GetCart("test")
		if err != nil {
			errors = append(errors, fmt.Sprintf("CartService.getCart failed: %v", err))
			return
		}
		_ = result // Use result to avoid unused variable
		fmt.Printf("✓ CartService.getCart passed\n")
	}()

	// Test CartService.clearCart
	func() {
		defer func() {
			if r := recover(); r != nil {
				errors = append(errors, fmt.Sprintf("CartService.clearCart failed: %v", r))
			}
		}()
		result, err := cartserviceClient.ClearCart("test")
		if err != nil {
			errors = append(errors, fmt.Sprintf("CartService.clearCart failed: %v", err))
			return
		}
		_ = result // Use result to avoid unused variable
		fmt.Printf("✓ CartService.clearCart passed\n")
	}()

	// Test OrderService.createOrder
	func() {
		defer func() {
			if r := recover(); r != nil {
				errors = append(errors, fmt.Sprintf("OrderService.createOrder failed: %v", r))
			}
		}()
		result, err := orderserviceClient.CreateOrder(CreateOrderRequest{CartId: "test", ShippingAddress: Address{Street: "test", City: "test", State: "test", ZipCode: "test", Country: "test"}, PaymentMethod: PaymentMethodCreditCard})
		if err != nil {
			errors = append(errors, fmt.Sprintf("OrderService.createOrder failed: %v", err))
			return
		}
		_ = result // Use result to avoid unused variable
		fmt.Printf("✓ OrderService.createOrder passed\n")
	}()

	// Test OrderService.getOrder
	func() {
		defer func() {
			if r := recover(); r != nil {
				errors = append(errors, fmt.Sprintf("OrderService.getOrder failed: %v", r))
			}
		}()
		result, err := orderserviceClient.GetOrder("test")
		if err != nil {
			errors = append(errors, fmt.Sprintf("OrderService.getOrder failed: %v", err))
			return
		}
		_ = result // Use result to avoid unused variable
		fmt.Printf("✓ OrderService.getOrder passed\n")
	}()

	fmt.Println()
	if len(errors) > 0 {
		fmt.Fprintf(os.Stderr, "FAILED: %d test(s) failed:\n", len(errors))
		for _, err := range errors {
			fmt.Fprintf(os.Stderr, "  - %s\n", err)
		}
		os.Exit(1)
	} else {
		fmt.Println("SUCCESS: All tests passed!")
		os.Exit(0)
	}
}
