// +build !test_client

// Generated by barrister - do not edit
// Test server implementation for integration testing

package main

import (
	// No imports needed for stub implementations
)

type CatalogServiceImpl struct{}

func (i *CatalogServiceImpl) ListProducts() ([]Product, error) {
	// Return a valid list with a sample product to pass validation
	return []Product{
		{
			ProductId:   "prod-1",
			Name:        "Test Product",
			Description: "A test product",
			Price:       9.99,
			Stock:       100,
		},
	}, nil
}

func (i *CatalogServiceImpl) GetProduct(productId string) (*Product, error) {
	// Return a valid product to pass validation
	return &Product{
		ProductId:   productId,
		Name:        "Test Product",
		Description: "A test product",
		Price:       9.99,
		Stock:       100,
	}, nil
}

type CartServiceImpl struct{}

func (i *CartServiceImpl) AddToCart(request AddToCartRequest) (Cart, error) {
	// Return a valid cart with items to pass validation
	return Cart{
		CartId: "cart-1",
		Items: []CartItem{
			{
				ProductId: request.ProductId,
				Quantity:  request.Quantity,
			},
		},
	}, nil
}

func (i *CartServiceImpl) GetCart(cartId string) (*Cart, error) {
	// Return a valid cart to pass validation
	return &Cart{
		CartId: cartId,
		Items:  []CartItem{},
	}, nil
}

func (i *CartServiceImpl) ClearCart(cartId string) (bool, error) {
	var zero bool
	return zero, nil
}

type OrderServiceImpl struct{}

func (i *OrderServiceImpl) CreateOrder(request CreateOrderRequest) (CheckoutResponse, error) {
	// Return a valid checkout response to pass validation
	return CheckoutResponse{
		OrderId: "order-1",
		Status:  OrderStatusPending,
	}, nil
}

func (i *OrderServiceImpl) GetOrder(orderId string) (*Order, error) {
	// Return a valid order to pass validation
	return &Order{
		OrderId:        orderId,
		Status:         OrderStatusPending,
		PaymentMethod:  PaymentMethodCreditCard,
		ShippingAddress: Address{
			Street:   "123 Test St",
			City:     "Test City",
			State:    "TS",
			ZipCode:  "12345",
			Country:  "USA",
		},
	}, nil
}

func main() {
	server := NewBarristerServer("0.0.0.0", 8080)
	server.Register("CatalogService", &CatalogServiceImpl{})
	server.Register("CartService", &CartServiceImpl{})
	server.Register("OrderService", &OrderServiceImpl{})
	if err := server.ServeForever(); err != nil {
		panic(err)
	}
}
