# Generated by barrister - do not edit

from barrister2 import (
    RPCError,
    validate_type,
    validate_struct,
    validate_enum,
    find_struct,
    find_enum,
    get_struct_fields,
)

# IDL-specific type definitions for namespace: checkout
ALL_STRUCTS = {
    'Product': {
        'fields': [
            {
                'name': 'productId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'name',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'description',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'price',
                'type': {'builtIn': 'float'},
            },
            {
                'name': 'stock',
                'type': {'builtIn': 'int'},
            },
            {
                'name': 'imageUrl',
                'type': {'builtIn': 'string'},
                'optional': True,
            },
        ],
    },
    'CartItem': {
        'fields': [
            {
                'name': 'productId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'quantity',
                'type': {'builtIn': 'int'},
            },
            {
                'name': 'price',
                'type': {'builtIn': 'float'},
            },
        ],
    },
    'Cart': {
        'fields': [
            {
                'name': 'cartId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'items',
                'type': {'array': {'userDefined': 'CartItem'}},
            },
            {
                'name': 'subtotal',
                'type': {'builtIn': 'float'},
            },
        ],
    },
    'Address': {
        'fields': [
            {
                'name': 'street',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'city',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'state',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'zipCode',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'country',
                'type': {'builtIn': 'string'},
            },
        ],
    },
    'Order': {
        'fields': [
            {
                'name': 'orderId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'cart',
                'type': {'userDefined': 'Cart'},
            },
            {
                'name': 'shippingAddress',
                'type': {'userDefined': 'Address'},
            },
            {
                'name': 'paymentMethod',
                'type': {'userDefined': 'PaymentMethod'},
            },
            {
                'name': 'status',
                'type': {'userDefined': 'OrderStatus'},
            },
            {
                'name': 'total',
                'type': {'builtIn': 'float'},
            },
            {
                'name': 'createdAt',
                'type': {'builtIn': 'int'},
            },
        ],
    },
    'AddToCartRequest': {
        'fields': [
            {
                'name': 'cartId',
                'type': {'builtIn': 'string'},
                'optional': True,
            },
            {
                'name': 'productId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'quantity',
                'type': {'builtIn': 'int'},
            },
        ],
    },
    'CreateOrderRequest': {
        'fields': [
            {
                'name': 'cartId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'shippingAddress',
                'type': {'userDefined': 'Address'},
            },
            {
                'name': 'paymentMethod',
                'type': {'userDefined': 'PaymentMethod'},
            },
        ],
    },
    'CheckoutResponse': {
        'fields': [
            {
                'name': 'orderId',
                'type': {'builtIn': 'string'},
            },
            {
                'name': 'message',
                'type': {'builtIn': 'string'},
                'optional': True,
            },
        ],
    },
}

ALL_ENUMS = {
    'OrderStatus': {
        'values': [
            {'name': 'pending'},
            {'name': 'paid'},
            {'name': 'shipped'},
            {'name': 'delivered'},
            {'name': 'cancelled'},
        ],
    },
    'PaymentMethod': {
        'values': [
            {'name': 'credit_card'},
            {'name': 'debit_card'},
            {'name': 'paypal'},
            {'name': 'apple_pay'},
        ],
    },
}
