# Generated by barrister - do not edit

from abc import ABC, abstractmethod
from typing import Dict, Any, Optional, List
import json
import sys
import urllib.request
import urllib.error
import uuid
from pathlib import Path

from barrister2 import RPCError, validate_type
from checkout import ALL_STRUCTS as CHECKOUT_STRUCTS, ALL_ENUMS as CHECKOUT_ENUMS

# Merge ALL_STRUCTS and ALL_ENUMS from all namespaces
ALL_STRUCTS = {}
ALL_STRUCTS.update(CHECKOUT_STRUCTS)

ALL_ENUMS = {}
ALL_ENUMS.update(CHECKOUT_ENUMS)

class Transport(ABC):
    """Abstract base class for transport implementations.
    
    Transports handle the roundtrip of sending requests to the server
    and decoding responses. Different transports can use different
    protocols (HTTP, ZeroMQ, etc.) and serialization formats (JSON, MessagePack, etc.).
    """

    @abstractmethod
    def call(self, method: str, params: list) -> dict:
        """Perform a JSON-RPC 2.0 call and return the response.
        
        Args:
            method: The method name in format 'interface.method'
            params: List of parameters to pass to the method
        
        Returns:
            dict: The JSON-RPC 2.0 response dictionary
        
        Raises:
            RPCError: If the JSON-RPC call returns an error
            Exception: For transport-level errors (network, etc.)
        """
        pass


class HTTPTransport(Transport):
    """HTTP transport implementation using JSON-RPC 2.0 over HTTP.
    
    Uses Python's standard library urllib.request for HTTP requests.
    Supports configurable headers for authentication and other purposes.
    """

    def __init__(self, base_url: str, headers: Optional[Dict[str, str]] = None):
        """Initialize HTTP transport.
        
        Args:
            base_url: Base URL of the server (e.g., 'http://localhost:8080')
            headers: Optional dictionary of HTTP headers to include with each request
        """
        self.base_url = base_url.rstrip('/')
        self.headers = headers.copy() if headers else {}

    def call(self, method: str, params: list) -> dict:
        """Perform a JSON-RPC 2.0 call over HTTP.
        
        Args:
            method: The method name in format 'interface.method'
            params: List of parameters to pass to the method
        
        Returns:
            dict: The JSON-RPC 2.0 response dictionary
        
        Raises:
            RPCError: If the JSON-RPC call returns an error
            urllib.error.HTTPError: For HTTP errors
            urllib.error.URLError: For network errors
        """
        # Generate request ID
        request_id = str(uuid.uuid4())

        # Build JSON-RPC 2.0 request
        request_data = {
            'jsonrpc': '2.0',
            'method': method,
            'params': params,
            'id': request_id
        }

        # Serialize to JSON
        json_data = json.dumps(request_data).encode('utf-8')

        # Prepare request
        req = urllib.request.Request(self.base_url, data=json_data, method='POST')
        req.add_header('Content-Type', 'application/json')
        req.add_header('Content-Length', str(len(json_data)))

        # Add custom headers
        for key, value in self.headers.items():
            req.add_header(key, value)

        try:
            # Send request
            with urllib.request.urlopen(req) as response:
                response_body = response.read().decode('utf-8')
                response_data = json.loads(response_body)

                # Check for JSON-RPC error
                if 'error' in response_data:
                    error = response_data['error']
                    code = error.get('code', -32603)
                    message = error.get('message', 'Internal error')
                    data = error.get('data')
                    raise RPCError(code, message, data)

                # Return response
                return response_data

        except urllib.error.HTTPError as e:
            # Try to parse error response as JSON-RPC
            try:
                error_body = e.read().decode('utf-8')
                error_data = json.loads(error_body)
                if 'error' in error_data:
                    error = error_data['error']
                    code = error.get('code', -32603)
                    message = error.get('message', 'Internal error')
                    data = error.get('data')
                    raise RPCError(code, message, data)
            except (json.JSONDecodeError, UnicodeDecodeError):
                pass
            # If not JSON-RPC error, raise HTTP error
            raise RPCError(-32603, f"HTTP error: {e.code} {e.reason}", None)
        except urllib.error.URLError as e:
            raise RPCError(-32603, f"Network error: {e.reason}", None)


class CatalogServiceClient:
    """Client for CatalogService interface."""

    def __init__(self, transport: Transport):
        """Initialize client with a transport.

        Args:
            transport: Transport instance to use for RPC calls
        """
        self.transport = transport

        # Method definitions for validation
        self._method_defs = {
            'listProducts': {
                'parameters': [
                ],
                'returnType': {'array': {'userDefined': 'Product'}},
                'returnOptional': False,
            },
            'getProduct': {
                'parameters': [
                    {
                        'name': 'productId',
                        'type': {'builtIn': 'string'},
                    },
                ],
                'returnType': {'userDefined': 'Product'},
                'returnOptional': True,
            },
        }

    def listProducts(self):
        """Call CatalogService.listProducts.

        Returns:
            The method return value

        Raises:
            RPCError: If the RPC call fails
        """
        method_def = self._method_defs['listProducts']
        params = [
        ]

        # Validate parameters
        expected_params = method_def.get('parameters', [])
        for i, (param_value, param_def) in enumerate(zip(params, expected_params)):
            try:
                validate_type(param_value, param_def['type'], ALL_STRUCTS, ALL_ENUMS, False)
            except Exception as e:
                raise ValueError(f"Parameter {i} ({param_def['name']}) validation failed: {e}")

        # Call transport
        method_name = 'CatalogService.listProducts'
        response = self.transport.call(method_name, params)

        # Extract result from JSON-RPC response
        if 'error' in response:
            error = response['error']
            code = error.get('code', -32603)
            message = error.get('message', 'Internal error')
            data = error.get('data')
            raise RPCError(code, message, data)

        result = response.get('result')

        # Validate result
        return_type = method_def.get('returnType')
        return_optional = method_def.get('returnOptional', False)
        if return_type:
            try:
                validate_type(result, return_type, ALL_STRUCTS, ALL_ENUMS, return_optional)
            except Exception as e:
                raise ValueError(f"Response validation failed: {e}")

        return result

    def getProduct(self, productId):
        """Call CatalogService.getProduct.

        Args:
            productId: Parameter productId

        Returns:
            The method return value

        Raises:
            RPCError: If the RPC call fails
        """
        method_def = self._method_defs['getProduct']
        params = [
            productId,
        ]

        # Validate parameters
        expected_params = method_def.get('parameters', [])
        for i, (param_value, param_def) in enumerate(zip(params, expected_params)):
            try:
                validate_type(param_value, param_def['type'], ALL_STRUCTS, ALL_ENUMS, False)
            except Exception as e:
                raise ValueError(f"Parameter {i} ({param_def['name']}) validation failed: {e}")

        # Call transport
        method_name = 'CatalogService.getProduct'
        response = self.transport.call(method_name, params)

        # Extract result from JSON-RPC response
        if 'error' in response:
            error = response['error']
            code = error.get('code', -32603)
            message = error.get('message', 'Internal error')
            data = error.get('data')
            raise RPCError(code, message, data)

        result = response.get('result')

        # Validate result
        return_type = method_def.get('returnType')
        return_optional = method_def.get('returnOptional', False)
        if return_type:
            try:
                validate_type(result, return_type, ALL_STRUCTS, ALL_ENUMS, return_optional)
            except Exception as e:
                raise ValueError(f"Response validation failed: {e}")

        return result


class CartServiceClient:
    """Client for CartService interface."""

    def __init__(self, transport: Transport):
        """Initialize client with a transport.

        Args:
            transport: Transport instance to use for RPC calls
        """
        self.transport = transport

        # Method definitions for validation
        self._method_defs = {
            'addToCart': {
                'parameters': [
                    {
                        'name': 'request',
                        'type': {'userDefined': 'AddToCartRequest'},
                    },
                ],
                'returnType': {'userDefined': 'Cart'},
                'returnOptional': False,
            },
            'getCart': {
                'parameters': [
                    {
                        'name': 'cartId',
                        'type': {'builtIn': 'string'},
                    },
                ],
                'returnType': {'userDefined': 'Cart'},
                'returnOptional': True,
            },
            'clearCart': {
                'parameters': [
                    {
                        'name': 'cartId',
                        'type': {'builtIn': 'string'},
                    },
                ],
                'returnType': {'builtIn': 'bool'},
                'returnOptional': False,
            },
        }

    def addToCart(self, request):
        """Call CartService.addToCart.

        Args:
            request: Parameter request

        Returns:
            The method return value

        Raises:
            RPCError: If the RPC call fails
        """
        method_def = self._method_defs['addToCart']
        params = [
            request,
        ]

        # Validate parameters
        expected_params = method_def.get('parameters', [])
        for i, (param_value, param_def) in enumerate(zip(params, expected_params)):
            try:
                validate_type(param_value, param_def['type'], ALL_STRUCTS, ALL_ENUMS, False)
            except Exception as e:
                raise ValueError(f"Parameter {i} ({param_def['name']}) validation failed: {e}")

        # Call transport
        method_name = 'CartService.addToCart'
        response = self.transport.call(method_name, params)

        # Extract result from JSON-RPC response
        if 'error' in response:
            error = response['error']
            code = error.get('code', -32603)
            message = error.get('message', 'Internal error')
            data = error.get('data')
            raise RPCError(code, message, data)

        result = response.get('result')

        # Validate result
        return_type = method_def.get('returnType')
        return_optional = method_def.get('returnOptional', False)
        if return_type:
            try:
                validate_type(result, return_type, ALL_STRUCTS, ALL_ENUMS, return_optional)
            except Exception as e:
                raise ValueError(f"Response validation failed: {e}")

        return result

    def getCart(self, cartId):
        """Call CartService.getCart.

        Args:
            cartId: Parameter cartId

        Returns:
            The method return value

        Raises:
            RPCError: If the RPC call fails
        """
        method_def = self._method_defs['getCart']
        params = [
            cartId,
        ]

        # Validate parameters
        expected_params = method_def.get('parameters', [])
        for i, (param_value, param_def) in enumerate(zip(params, expected_params)):
            try:
                validate_type(param_value, param_def['type'], ALL_STRUCTS, ALL_ENUMS, False)
            except Exception as e:
                raise ValueError(f"Parameter {i} ({param_def['name']}) validation failed: {e}")

        # Call transport
        method_name = 'CartService.getCart'
        response = self.transport.call(method_name, params)

        # Extract result from JSON-RPC response
        if 'error' in response:
            error = response['error']
            code = error.get('code', -32603)
            message = error.get('message', 'Internal error')
            data = error.get('data')
            raise RPCError(code, message, data)

        result = response.get('result')

        # Validate result
        return_type = method_def.get('returnType')
        return_optional = method_def.get('returnOptional', False)
        if return_type:
            try:
                validate_type(result, return_type, ALL_STRUCTS, ALL_ENUMS, return_optional)
            except Exception as e:
                raise ValueError(f"Response validation failed: {e}")

        return result

    def clearCart(self, cartId):
        """Call CartService.clearCart.

        Args:
            cartId: Parameter cartId

        Returns:
            The method return value

        Raises:
            RPCError: If the RPC call fails
        """
        method_def = self._method_defs['clearCart']
        params = [
            cartId,
        ]

        # Validate parameters
        expected_params = method_def.get('parameters', [])
        for i, (param_value, param_def) in enumerate(zip(params, expected_params)):
            try:
                validate_type(param_value, param_def['type'], ALL_STRUCTS, ALL_ENUMS, False)
            except Exception as e:
                raise ValueError(f"Parameter {i} ({param_def['name']}) validation failed: {e}")

        # Call transport
        method_name = 'CartService.clearCart'
        response = self.transport.call(method_name, params)

        # Extract result from JSON-RPC response
        if 'error' in response:
            error = response['error']
            code = error.get('code', -32603)
            message = error.get('message', 'Internal error')
            data = error.get('data')
            raise RPCError(code, message, data)

        result = response.get('result')

        # Validate result
        return_type = method_def.get('returnType')
        return_optional = method_def.get('returnOptional', False)
        if return_type:
            try:
                validate_type(result, return_type, ALL_STRUCTS, ALL_ENUMS, return_optional)
            except Exception as e:
                raise ValueError(f"Response validation failed: {e}")

        return result


class OrderServiceClient:
    """Client for OrderService interface."""

    def __init__(self, transport: Transport):
        """Initialize client with a transport.

        Args:
            transport: Transport instance to use for RPC calls
        """
        self.transport = transport

        # Method definitions for validation
        self._method_defs = {
            'createOrder': {
                'parameters': [
                    {
                        'name': 'request',
                        'type': {'userDefined': 'CreateOrderRequest'},
                    },
                ],
                'returnType': {'userDefined': 'CheckoutResponse'},
                'returnOptional': False,
            },
            'getOrder': {
                'parameters': [
                    {
                        'name': 'orderId',
                        'type': {'builtIn': 'string'},
                    },
                ],
                'returnType': {'userDefined': 'Order'},
                'returnOptional': True,
            },
        }

    def createOrder(self, request):
        """Call OrderService.createOrder.

        Args:
            request: Parameter request

        Returns:
            The method return value

        Raises:
            RPCError: If the RPC call fails
        """
        method_def = self._method_defs['createOrder']
        params = [
            request,
        ]

        # Validate parameters
        expected_params = method_def.get('parameters', [])
        for i, (param_value, param_def) in enumerate(zip(params, expected_params)):
            try:
                validate_type(param_value, param_def['type'], ALL_STRUCTS, ALL_ENUMS, False)
            except Exception as e:
                raise ValueError(f"Parameter {i} ({param_def['name']}) validation failed: {e}")

        # Call transport
        method_name = 'OrderService.createOrder'
        response = self.transport.call(method_name, params)

        # Extract result from JSON-RPC response
        if 'error' in response:
            error = response['error']
            code = error.get('code', -32603)
            message = error.get('message', 'Internal error')
            data = error.get('data')
            raise RPCError(code, message, data)

        result = response.get('result')

        # Validate result
        return_type = method_def.get('returnType')
        return_optional = method_def.get('returnOptional', False)
        if return_type:
            try:
                validate_type(result, return_type, ALL_STRUCTS, ALL_ENUMS, return_optional)
            except Exception as e:
                raise ValueError(f"Response validation failed: {e}")

        return result

    def getOrder(self, orderId):
        """Call OrderService.getOrder.

        Args:
            orderId: Parameter orderId

        Returns:
            The method return value

        Raises:
            RPCError: If the RPC call fails
        """
        method_def = self._method_defs['getOrder']
        params = [
            orderId,
        ]

        # Validate parameters
        expected_params = method_def.get('parameters', [])
        for i, (param_value, param_def) in enumerate(zip(params, expected_params)):
            try:
                validate_type(param_value, param_def['type'], ALL_STRUCTS, ALL_ENUMS, False)
            except Exception as e:
                raise ValueError(f"Parameter {i} ({param_def['name']}) validation failed: {e}")

        # Call transport
        method_name = 'OrderService.getOrder'
        response = self.transport.call(method_name, params)

        # Extract result from JSON-RPC response
        if 'error' in response:
            error = response['error']
            code = error.get('code', -32603)
            message = error.get('message', 'Internal error')
            data = error.get('data')
            raise RPCError(code, message, data)

        result = response.get('result')

        # Validate result
        return_type = method_def.get('returnType')
        return_optional = method_def.get('returnOptional', False)
        if return_type:
            try:
                validate_type(result, return_type, ALL_STRUCTS, ALL_ENUMS, return_optional)
            except Exception as e:
                raise ValueError(f"Response validation failed: {e}")

        return result


