# Generated by barrister - do not edit
# Test server implementation for integration testing

import math
from server import BarristerServer
from server import CatalogService
from server import CartService
from server import OrderService

class CatalogServiceImpl(CatalogService):
    """Test implementation of CatalogService interface"""

    def __init__(self):
        pass

    def listProducts(self):
        return []

    def getProduct(self, productId):
        return {
            'productId': "",
            'name': "",
            'description': "",
            'price': 0.0,
            'stock': 0,
        }


class CartServiceImpl(CartService):
    """Test implementation of CartService interface"""

    def __init__(self):
        pass

    def addToCart(self, request):
        return {
            'cartId': "",
            'items': [],
            'subtotal': 0.0,
        }

    def getCart(self, cartId):
        return {
            'cartId': "",
            'items': [],
            'subtotal': 0.0,
        }

    def clearCart(self, cartId):
        return False


class OrderServiceImpl(OrderService):
    """Test implementation of OrderService interface"""

    def __init__(self):
        pass

    def createOrder(self, request):
        return {
            'orderId': "",
        }

    def getOrder(self, orderId):
        return {
            'orderId': "",
            'cart': {},
            'shippingAddress': {},
            'paymentMethod': "credit_card",
            'status': "pending",
            'total': 0.0,
            'createdAt': 0,
        }


if __name__ == "__main__":
    server = BarristerServer(host="0.0.0.0", port=8080)
    server.register("CatalogService", CatalogServiceImpl())
    server.register("CartService", CartServiceImpl())
    server.register("OrderService", OrderServiceImpl())
    server.serve_forever()
