# Generated by barrister - do not edit
# Test server implementation for integration testing

import math
from server import BarristerServer
from server import CatalogService
from server import CartService
from server import OrderService

class CatalogServiceImpl(CatalogService):
    """Test implementation of CatalogService interface"""

    def __init__(self):
        pass

    def listProducts(self):
        # Return a valid list with a sample product to pass validation
        return [{
            'productId': "prod-1",
            'name': "Test Product",
            'description': "A test product",
            'price': 9.99,
            'stock': 100,
        }]

    def getProduct(self, productId):
        # Return a valid product to pass validation
        return {
            'productId': productId,
            'name': "Test Product",
            'description': "A test product",
            'price': 9.99,
            'stock': 100,
        }


class CartServiceImpl(CartService):
    """Test implementation of CartService interface"""

    def __init__(self):
        pass

    def addToCart(self, request):
        # Return a valid cart with items to pass validation
        return {
            'cartId': "cart-1",
            'items': [{
                'productId': request['productId'],
                'quantity': request['quantity'],
                'price': 9.99,
            }],
            'subtotal': 9.99,
        }

    def getCart(self, cartId):
        # Return a valid cart to pass validation
        return {
            'cartId': cartId,
            'items': [],
            'subtotal': 0.0,
        }

    def clearCart(self, cartId):
        return True


class OrderServiceImpl(OrderService):
    """Test implementation of OrderService interface"""

    def __init__(self):
        pass

    def createOrder(self, request):
        # Return a valid checkout response to pass validation
        return {
            'orderId': "order-1",
        }

    def getOrder(self, orderId):
        # Return a valid order to pass validation
        return {
            'orderId': orderId,
            'cart': {
                'cartId': "cart-1",
                'items': [],
                'subtotal': 0.0,
            },
            'shippingAddress': {
                'street': "123 Test St",
                'city': "Test City",
                'state': "TS",
                'zipCode': "12345",
                'country': "USA",
            },
            'paymentMethod': "credit_card",
            'status': "pending",
            'total': 0.0,
            'createdAt': 0,
        }


if __name__ == "__main__":
    server = BarristerServer(host="0.0.0.0", port=8080)
    server.register("CatalogService", CatalogServiceImpl())
    server.register("CartService", CartServiceImpl())
    server.register("OrderService", OrderServiceImpl())
    server.serve_forever()
