# Generated by barrister - do not edit
# Test client for integration testing

import sys
import time
import urllib.request
from client import HTTPTransport

from client import CatalogServiceClient
from client import CartServiceClient
from client import OrderServiceClient

def wait_for_server(url: str, timeout: int = 10) -> bool:
    """Wait for server to be ready"""
    import urllib.error
    start_time = time.time()
    while time.time() - start_time < timeout:
        try:
            req = urllib.request.Request(url, method='POST')
            req.add_header('Content-Type', 'application/json')
            urllib.request.urlopen(req, data=b'{}', timeout=1)
            return True
        except (urllib.error.URLError, urllib.error.HTTPError):
            time.sleep(0.5)
    return False

def main():
    server_url = "http://localhost:8080"
    
    # Wait for server to be ready
    print("Waiting for server to be ready...")
    if not wait_for_server(server_url, timeout=10):
        print("ERROR: Server did not become ready in time")
        sys.exit(1)
    
    print("Server is ready. Running tests...")
    print()
    
    # Create transport and clients
    transport = HTTPTransport(server_url)
    catalogservice_client = CatalogServiceClient(transport)
    cartservice_client = CartServiceClient(transport)
    orderservice_client = OrderServiceClient(transport)
    
    errors = []
    
    # Test CatalogService.listProducts
    try:
        result = catalogservice_client.listProducts()
        assert result is not None, "Expected non-None result"
        print("✓ CatalogService.listProducts passed")
    except Exception as e:
        error_msg = "CatalogService.listProducts failed: {}".format(str(e))
        errors.append(error_msg)
        print(f"✗ {error_msg}")
    
    # Test CatalogService.getProduct
    try:
        result = catalogservice_client.getProduct("test")
        assert result is not None, "Expected non-None result"
        print("✓ CatalogService.getProduct passed")
    except Exception as e:
        error_msg = "CatalogService.getProduct failed: {}".format(str(e))
        errors.append(error_msg)
        print(f"✗ {error_msg}")
    
    # Test CartService.addToCart
    try:
        result = cartservice_client.addToCart({'productId': "test", 'quantity': 1})
        assert result is not None, "Expected non-None result"
        print("✓ CartService.addToCart passed")
    except Exception as e:
        error_msg = "CartService.addToCart failed: {}".format(str(e))
        errors.append(error_msg)
        print(f"✗ {error_msg}")
    
    # Test CartService.getCart
    try:
        result = cartservice_client.getCart("test")
        assert result is not None, "Expected non-None result"
        print("✓ CartService.getCart passed")
    except Exception as e:
        error_msg = "CartService.getCart failed: {}".format(str(e))
        errors.append(error_msg)
        print(f"✗ {error_msg}")
    
    # Test CartService.clearCart
    try:
        result = cartservice_client.clearCart("test")
        assert result is not None, "Expected non-None result"
        print("✓ CartService.clearCart passed")
    except Exception as e:
        error_msg = "CartService.clearCart failed: {}".format(str(e))
        errors.append(error_msg)
        print(f"✗ {error_msg}")
    
    # Test OrderService.createOrder
    try:
        result = orderservice_client.createOrder({'cartId': "test", 'shippingAddress': {'street': "test", 'city': "test", 'state': "test", 'zipCode': "test", 'country': "test"}, 'paymentMethod': "credit_card"})
        assert result is not None, "Expected non-None result"
        print("✓ OrderService.createOrder passed")
    except Exception as e:
        error_msg = "OrderService.createOrder failed: {}".format(str(e))
        errors.append(error_msg)
        print(f"✗ {error_msg}")
    
    # Test OrderService.getOrder
    try:
        result = orderservice_client.getOrder("test")
        assert result is not None, "Expected non-None result"
        print("✓ OrderService.getOrder passed")
    except Exception as e:
        error_msg = "OrderService.getOrder failed: {}".format(str(e))
        errors.append(error_msg)
        print(f"✗ {error_msg}")
    
    # Report results
    print()
    if errors:
        print(f"FAILED: {len(errors)} test(s) failed:")
        for error in errors:
            print(f"  - {error}")
        sys.exit(1)
    else:
        print("SUCCESS: All tests passed!")
        sys.exit(0)

if __name__ == "__main__":
    main()
