// Generated by barrister - do not edit

package checkout

type OrderStatus string

const (
	OrderStatusPending OrderStatus = "pending"
	OrderStatusPaid OrderStatus = "paid"
	OrderStatusShipped OrderStatus = "shipped"
	OrderStatusDelivered OrderStatus = "delivered"
	OrderStatusCancelled OrderStatus = "cancelled"
)

type PaymentMethod string

const (
	PaymentMethodCreditCard PaymentMethod = "credit_card"
	PaymentMethodDebitCard PaymentMethod = "debit_card"
	PaymentMethodPaypal PaymentMethod = "paypal"
	PaymentMethodApplePay PaymentMethod = "apple_pay"
)


type Product struct {
	ProductId string `json:"productId"`
	Name string `json:"name"`
	Description string `json:"description"`
	Price float64 `json:"price"`
	Stock int `json:"stock"`
	ImageUrl *string `json:"imageUrl,omitempty"`
}

type CartItem struct {
	ProductId string `json:"productId"`
	Quantity int `json:"quantity"`
	Price float64 `json:"price"`
}

type Cart struct {
	CartId string `json:"cartId"`
	Items []CartItem `json:"items"`
	Subtotal float64 `json:"subtotal"`
}

type Address struct {
	Street string `json:"street"`
	City string `json:"city"`
	State string `json:"state"`
	ZipCode string `json:"zipCode"`
	Country string `json:"country"`
}

type Order struct {
	OrderId string `json:"orderId"`
	Cart Cart `json:"cart"`
	ShippingAddress Address `json:"shippingAddress"`
	PaymentMethod PaymentMethod `json:"paymentMethod"`
	Status OrderStatus `json:"status"`
	Total float64 `json:"total"`
	CreatedAt int `json:"createdAt"`
}

type AddToCartRequest struct {
	CartId *string `json:"cartId,omitempty"`
	ProductId string `json:"productId"`
	Quantity int `json:"quantity"`
}

type CreateOrderRequest struct {
	CartId string `json:"cartId"`
	ShippingAddress Address `json:"shippingAddress"`
	PaymentMethod PaymentMethod `json:"paymentMethod"`
}

type CheckoutResponse struct {
	OrderId string `json:"orderId"`
	Message *string `json:"message,omitempty"`
}


// IDL-specific type definitions for namespace: checkout
var CHECKOUT_ALL_STRUCTS = StructMap{
	"Product": StructDef{
		"fields": []interface{}{
			map[string]interface{}{
				"name": "productId",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "name",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "description",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "price",
				"type": map[string]interface{}{"builtIn": "float"},
			},
			map[string]interface{}{
				"name": "stock",
				"type": map[string]interface{}{"builtIn": "int"},
			},
			map[string]interface{}{
				"name": "imageUrl",
				"type": map[string]interface{}{"builtIn": "string"},
				"optional": true,
			},
		},
	},
	"CartItem": StructDef{
		"fields": []interface{}{
			map[string]interface{}{
				"name": "productId",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "quantity",
				"type": map[string]interface{}{"builtIn": "int"},
			},
			map[string]interface{}{
				"name": "price",
				"type": map[string]interface{}{"builtIn": "float"},
			},
		},
	},
	"Cart": StructDef{
		"fields": []interface{}{
			map[string]interface{}{
				"name": "cartId",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "items",
				"type": map[string]interface{}{"array": map[string]interface{}{"userDefined": "CartItem"}},
			},
			map[string]interface{}{
				"name": "subtotal",
				"type": map[string]interface{}{"builtIn": "float"},
			},
		},
	},
	"Address": StructDef{
		"fields": []interface{}{
			map[string]interface{}{
				"name": "street",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "city",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "state",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "zipCode",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "country",
				"type": map[string]interface{}{"builtIn": "string"},
			},
		},
	},
	"Order": StructDef{
		"fields": []interface{}{
			map[string]interface{}{
				"name": "orderId",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "cart",
				"type": map[string]interface{}{"userDefined": "Cart"},
			},
			map[string]interface{}{
				"name": "shippingAddress",
				"type": map[string]interface{}{"userDefined": "Address"},
			},
			map[string]interface{}{
				"name": "paymentMethod",
				"type": map[string]interface{}{"userDefined": "PaymentMethod"},
			},
			map[string]interface{}{
				"name": "status",
				"type": map[string]interface{}{"userDefined": "OrderStatus"},
			},
			map[string]interface{}{
				"name": "total",
				"type": map[string]interface{}{"builtIn": "float"},
			},
			map[string]interface{}{
				"name": "createdAt",
				"type": map[string]interface{}{"builtIn": "int"},
			},
		},
	},
	"AddToCartRequest": StructDef{
		"fields": []interface{}{
			map[string]interface{}{
				"name": "cartId",
				"type": map[string]interface{}{"builtIn": "string"},
				"optional": true,
			},
			map[string]interface{}{
				"name": "productId",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "quantity",
				"type": map[string]interface{}{"builtIn": "int"},
			},
		},
	},
	"CreateOrderRequest": StructDef{
		"fields": []interface{}{
			map[string]interface{}{
				"name": "cartId",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "shippingAddress",
				"type": map[string]interface{}{"userDefined": "Address"},
			},
			map[string]interface{}{
				"name": "paymentMethod",
				"type": map[string]interface{}{"userDefined": "PaymentMethod"},
			},
		},
	},
	"CheckoutResponse": StructDef{
		"fields": []interface{}{
			map[string]interface{}{
				"name": "orderId",
				"type": map[string]interface{}{"builtIn": "string"},
			},
			map[string]interface{}{
				"name": "message",
				"type": map[string]interface{}{"builtIn": "string"},
				"optional": true,
			},
		},
	},
}

var CHECKOUT_ALL_ENUMS = EnumMap{
	"OrderStatus": EnumDef{
		"values": []interface{}{
			map[string]interface{}{
				"name": "pending",
			},
			map[string]interface{}{
				"name": "paid",
			},
			map[string]interface{}{
				"name": "shipped",
			},
			map[string]interface{}{
				"name": "delivered",
			},
			map[string]interface{}{
				"name": "cancelled",
			},
		},
	},
	"PaymentMethod": EnumDef{
		"values": []interface{}{
			map[string]interface{}{
				"name": "credit_card",
			},
			map[string]interface{}{
				"name": "debit_card",
			},
			map[string]interface{}{
				"name": "paypal",
			},
			map[string]interface{}{
				"name": "apple_pay",
			},
		},
	},
}
// NewRPCError creates a new RPCError with the given code and message
func NewRPCError(code int, message string) *RPCError {
	return NewRPCError(code, message)
}

