//go:build !server_only
// +build !server_only

// Generated by barrister - do not edit

package checkout

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
)

// Merge ALL_STRUCTS and ALL_ENUMS from all namespaces
var ALL_STRUCTS = StructMap{}
var ALL_ENUMS = EnumMap{}

func init() {
	for k, v := range CHECKOUT_ALL_STRUCTS {
		ALL_STRUCTS[k] = v
	}
	for k, v := range CHECKOUT_ALL_ENUMS {
		ALL_ENUMS[k] = v
	}
}

// Transport is an interface for making JSON-RPC 2.0 calls
type Transport interface {
	Call(method string, params []interface{}) (map[string]interface{}, error)
}

// HTTPTransport implements Transport using HTTP
type HTTPTransport struct {
	baseURL string
	headers map[string]string
	client  *http.Client
}

// NewHTTPTransport creates a new HTTPTransport
func NewHTTPTransport(baseURL string, headers map[string]string) *HTTPTransport {
	if headers == nil {
		headers = make(map[string]string)
	}
	return &HTTPTransport{
		baseURL: strings.TrimSuffix(baseURL, "/"),
		headers: headers,
		client:  &http.Client{},
	}
}

// Call performs a JSON-RPC 2.0 call over HTTP
func (t *HTTPTransport) Call(method string, params []interface{}) (map[string]interface{}, error) {
	requestID := fmt.Sprintf("%d", len(method)+len(params))
	request := map[string]interface{}{
		"jsonrpc": "2.0",
		"method":  method,
		"params":  params,
		"id":      requestID,
	}

	jsonData, err := json.Marshal(request)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	req, err := http.NewRequest("POST", t.baseURL, bytes.NewBuffer(jsonData))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")
	for k, v := range t.headers {
		req.Header.Set(k, v)
	}

	resp, err := t.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("HTTP request failed: %w", err)
	}
	defer resp.Body.Close()

	var response map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&response); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	if errObj, ok := response["error"].(map[string]interface{}); ok {
		code, _ := errObj["code"].(float64)
		message, _ := errObj["message"].(string)
		data := errObj["data"]
		return nil, &RPCError{
			Code:    int(code),
			Message: message,
			Data:    data,
		}
	}

	return response, nil
}

// CatalogServiceClient is a client for the CatalogService interface
type CatalogServiceClient struct {
	transport Transport
}

// NewCatalogServiceClient creates a new CatalogServiceClient
func NewCatalogServiceClient(transport Transport) *CatalogServiceClient {
	return &CatalogServiceClient{transport: transport}
}

// ListProducts calls CatalogService.listProducts
func (c *CatalogServiceClient) ListProducts() ([]Product, error) {
	params := []interface{}{
	}

	// Validate parameters
	methodDef := map[string]interface{}{
		"parameters": []interface{}{
		},
	}
	expectedParams, _ := methodDef["parameters"].([]interface{})
	for i, paramValue := range params {
		paramDef, _ := expectedParams[i].(map[string]interface{})
		paramType, _ := paramDef["type"].(map[string]interface{})
		// Convert param to interface{} for validation
		var paramInterface interface{}
		paramJSON, _ := json.Marshal(paramValue)
		json.Unmarshal(paramJSON, &paramInterface)
		if err := ValidateType(paramInterface, paramType, ALL_STRUCTS, ALL_ENUMS, false); err != nil {
			paramName, _ := paramDef["name"].(string)
			var zero []Product
			return zero, fmt.Errorf("parameter %d (%s) validation failed: %w", i, paramName, err)
		}
	}

	methodName := "CatalogService.listProducts"
	response, err := c.transport.Call(methodName, params)
	if err != nil {
		var zero []Product
		return zero, err
	}

	result, ok := response["result"]
	if !ok {
		var zero []Product
		return zero, fmt.Errorf("missing result in response")
	}

	// Validate result
	returnType := map[string]interface{}{"array": map[string]interface{}{"userDefined": "Product"}}
	returnOptional := false
	var resultInterface interface{}
	resultJSON, _ := json.Marshal(result)
	json.Unmarshal(resultJSON, &resultInterface)
	if err := ValidateType(resultInterface, returnType, ALL_STRUCTS, ALL_ENUMS, returnOptional); err != nil {
		var zero []Product
		return zero, fmt.Errorf("response validation failed: %w", err)
	}

	var typedResult []Product
	if err := json.Unmarshal(resultJSON, &typedResult); err != nil {
		var zero []Product
		return zero, fmt.Errorf("failed to unmarshal result: %w", err)
	}
	return typedResult, nil
}

// GetProduct calls CatalogService.getProduct
func (c *CatalogServiceClient) GetProduct(productId string) (*Product, error) {
	params := []interface{}{
		productId,
	}

	// Validate parameters
	methodDef := map[string]interface{}{
		"parameters": []interface{}{
			map[string]interface{}{
				"name": "productId",
				"type": map[string]interface{}{"builtIn": "string"},
			},
		},
	}
	expectedParams, _ := methodDef["parameters"].([]interface{})
	for i, paramValue := range params {
		paramDef, _ := expectedParams[i].(map[string]interface{})
		paramType, _ := paramDef["type"].(map[string]interface{})
		// Convert param to interface{} for validation
		var paramInterface interface{}
		paramJSON, _ := json.Marshal(paramValue)
		json.Unmarshal(paramJSON, &paramInterface)
		if err := ValidateType(paramInterface, paramType, ALL_STRUCTS, ALL_ENUMS, false); err != nil {
			paramName, _ := paramDef["name"].(string)
			var zero *Product
			return zero, fmt.Errorf("parameter %d (%s) validation failed: %w", i, paramName, err)
		}
	}

	methodName := "CatalogService.getProduct"
	response, err := c.transport.Call(methodName, params)
	if err != nil {
		var zero *Product
		return zero, err
	}

	result, ok := response["result"]
	if !ok {
		var zero *Product
		return zero, nil
	}

	// Validate result
	returnType := map[string]interface{}{"userDefined": "Product"}
	returnOptional := true
	var resultInterface interface{}
	resultJSON, _ := json.Marshal(result)
	json.Unmarshal(resultJSON, &resultInterface)
	if err := ValidateType(resultInterface, returnType, ALL_STRUCTS, ALL_ENUMS, returnOptional); err != nil {
		var zero *Product
		return zero, fmt.Errorf("response validation failed: %w", err)
	}

	var typedResult *Product
	if err := json.Unmarshal(resultJSON, &typedResult); err != nil {
		var zero *Product
		return zero, fmt.Errorf("failed to unmarshal result: %w", err)
	}
	return typedResult, nil
}

// CartServiceClient is a client for the CartService interface
type CartServiceClient struct {
	transport Transport
}

// NewCartServiceClient creates a new CartServiceClient
func NewCartServiceClient(transport Transport) *CartServiceClient {
	return &CartServiceClient{transport: transport}
}

// AddToCart calls CartService.addToCart
func (c *CartServiceClient) AddToCart(request AddToCartRequest) (Cart, error) {
	params := []interface{}{
		request,
	}

	// Validate parameters
	methodDef := map[string]interface{}{
		"parameters": []interface{}{
			map[string]interface{}{
				"name": "request",
				"type": map[string]interface{}{"userDefined": "AddToCartRequest"},
			},
		},
	}
	expectedParams, _ := methodDef["parameters"].([]interface{})
	for i, paramValue := range params {
		paramDef, _ := expectedParams[i].(map[string]interface{})
		paramType, _ := paramDef["type"].(map[string]interface{})
		// Convert param to interface{} for validation
		var paramInterface interface{}
		paramJSON, _ := json.Marshal(paramValue)
		json.Unmarshal(paramJSON, &paramInterface)
		if err := ValidateType(paramInterface, paramType, ALL_STRUCTS, ALL_ENUMS, false); err != nil {
			paramName, _ := paramDef["name"].(string)
			var zero Cart
			return zero, fmt.Errorf("parameter %d (%s) validation failed: %w", i, paramName, err)
		}
	}

	methodName := "CartService.addToCart"
	response, err := c.transport.Call(methodName, params)
	if err != nil {
		var zero Cart
		return zero, err
	}

	result, ok := response["result"]
	if !ok {
		var zero Cart
		return zero, fmt.Errorf("missing result in response")
	}

	// Validate result
	returnType := map[string]interface{}{"userDefined": "Cart"}
	returnOptional := false
	var resultInterface interface{}
	resultJSON, _ := json.Marshal(result)
	json.Unmarshal(resultJSON, &resultInterface)
	if err := ValidateType(resultInterface, returnType, ALL_STRUCTS, ALL_ENUMS, returnOptional); err != nil {
		var zero Cart
		return zero, fmt.Errorf("response validation failed: %w", err)
	}

	var typedResult Cart
	if err := json.Unmarshal(resultJSON, &typedResult); err != nil {
		var zero Cart
		return zero, fmt.Errorf("failed to unmarshal result: %w", err)
	}
	return typedResult, nil
}

// GetCart calls CartService.getCart
func (c *CartServiceClient) GetCart(cartId string) (*Cart, error) {
	params := []interface{}{
		cartId,
	}

	// Validate parameters
	methodDef := map[string]interface{}{
		"parameters": []interface{}{
			map[string]interface{}{
				"name": "cartId",
				"type": map[string]interface{}{"builtIn": "string"},
			},
		},
	}
	expectedParams, _ := methodDef["parameters"].([]interface{})
	for i, paramValue := range params {
		paramDef, _ := expectedParams[i].(map[string]interface{})
		paramType, _ := paramDef["type"].(map[string]interface{})
		// Convert param to interface{} for validation
		var paramInterface interface{}
		paramJSON, _ := json.Marshal(paramValue)
		json.Unmarshal(paramJSON, &paramInterface)
		if err := ValidateType(paramInterface, paramType, ALL_STRUCTS, ALL_ENUMS, false); err != nil {
			paramName, _ := paramDef["name"].(string)
			var zero *Cart
			return zero, fmt.Errorf("parameter %d (%s) validation failed: %w", i, paramName, err)
		}
	}

	methodName := "CartService.getCart"
	response, err := c.transport.Call(methodName, params)
	if err != nil {
		var zero *Cart
		return zero, err
	}

	result, ok := response["result"]
	if !ok {
		var zero *Cart
		return zero, nil
	}

	// Validate result
	returnType := map[string]interface{}{"userDefined": "Cart"}
	returnOptional := true
	var resultInterface interface{}
	resultJSON, _ := json.Marshal(result)
	json.Unmarshal(resultJSON, &resultInterface)
	if err := ValidateType(resultInterface, returnType, ALL_STRUCTS, ALL_ENUMS, returnOptional); err != nil {
		var zero *Cart
		return zero, fmt.Errorf("response validation failed: %w", err)
	}

	var typedResult *Cart
	if err := json.Unmarshal(resultJSON, &typedResult); err != nil {
		var zero *Cart
		return zero, fmt.Errorf("failed to unmarshal result: %w", err)
	}
	return typedResult, nil
}

// ClearCart calls CartService.clearCart
func (c *CartServiceClient) ClearCart(cartId string) (bool, error) {
	params := []interface{}{
		cartId,
	}

	// Validate parameters
	methodDef := map[string]interface{}{
		"parameters": []interface{}{
			map[string]interface{}{
				"name": "cartId",
				"type": map[string]interface{}{"builtIn": "string"},
			},
		},
	}
	expectedParams, _ := methodDef["parameters"].([]interface{})
	for i, paramValue := range params {
		paramDef, _ := expectedParams[i].(map[string]interface{})
		paramType, _ := paramDef["type"].(map[string]interface{})
		// Convert param to interface{} for validation
		var paramInterface interface{}
		paramJSON, _ := json.Marshal(paramValue)
		json.Unmarshal(paramJSON, &paramInterface)
		if err := ValidateType(paramInterface, paramType, ALL_STRUCTS, ALL_ENUMS, false); err != nil {
			paramName, _ := paramDef["name"].(string)
			var zero bool
			return zero, fmt.Errorf("parameter %d (%s) validation failed: %w", i, paramName, err)
		}
	}

	methodName := "CartService.clearCart"
	response, err := c.transport.Call(methodName, params)
	if err != nil {
		var zero bool
		return zero, err
	}

	result, ok := response["result"]
	if !ok {
		var zero bool
		return zero, fmt.Errorf("missing result in response")
	}

	// Validate result
	returnType := map[string]interface{}{"builtIn": "bool"}
	returnOptional := false
	var resultInterface interface{}
	resultJSON, _ := json.Marshal(result)
	json.Unmarshal(resultJSON, &resultInterface)
	if err := ValidateType(resultInterface, returnType, ALL_STRUCTS, ALL_ENUMS, returnOptional); err != nil {
		var zero bool
		return zero, fmt.Errorf("response validation failed: %w", err)
	}

	var typedResult bool
	if err := json.Unmarshal(resultJSON, &typedResult); err != nil {
		var zero bool
		return zero, fmt.Errorf("failed to unmarshal result: %w", err)
	}
	return typedResult, nil
}

// OrderServiceClient is a client for the OrderService interface
type OrderServiceClient struct {
	transport Transport
}

// NewOrderServiceClient creates a new OrderServiceClient
func NewOrderServiceClient(transport Transport) *OrderServiceClient {
	return &OrderServiceClient{transport: transport}
}

// CreateOrder calls OrderService.createOrder
func (c *OrderServiceClient) CreateOrder(request CreateOrderRequest) (CheckoutResponse, error) {
	params := []interface{}{
		request,
	}

	// Validate parameters
	methodDef := map[string]interface{}{
		"parameters": []interface{}{
			map[string]interface{}{
				"name": "request",
				"type": map[string]interface{}{"userDefined": "CreateOrderRequest"},
			},
		},
	}
	expectedParams, _ := methodDef["parameters"].([]interface{})
	for i, paramValue := range params {
		paramDef, _ := expectedParams[i].(map[string]interface{})
		paramType, _ := paramDef["type"].(map[string]interface{})
		// Convert param to interface{} for validation
		var paramInterface interface{}
		paramJSON, _ := json.Marshal(paramValue)
		json.Unmarshal(paramJSON, &paramInterface)
		if err := ValidateType(paramInterface, paramType, ALL_STRUCTS, ALL_ENUMS, false); err != nil {
			paramName, _ := paramDef["name"].(string)
			var zero CheckoutResponse
			return zero, fmt.Errorf("parameter %d (%s) validation failed: %w", i, paramName, err)
		}
	}

	methodName := "OrderService.createOrder"
	response, err := c.transport.Call(methodName, params)
	if err != nil {
		var zero CheckoutResponse
		return zero, err
	}

	result, ok := response["result"]
	if !ok {
		var zero CheckoutResponse
		return zero, fmt.Errorf("missing result in response")
	}

	// Validate result
	returnType := map[string]interface{}{"userDefined": "CheckoutResponse"}
	returnOptional := false
	var resultInterface interface{}
	resultJSON, _ := json.Marshal(result)
	json.Unmarshal(resultJSON, &resultInterface)
	if err := ValidateType(resultInterface, returnType, ALL_STRUCTS, ALL_ENUMS, returnOptional); err != nil {
		var zero CheckoutResponse
		return zero, fmt.Errorf("response validation failed: %w", err)
	}

	var typedResult CheckoutResponse
	if err := json.Unmarshal(resultJSON, &typedResult); err != nil {
		var zero CheckoutResponse
		return zero, fmt.Errorf("failed to unmarshal result: %w", err)
	}
	return typedResult, nil
}

// GetOrder calls OrderService.getOrder
func (c *OrderServiceClient) GetOrder(orderId string) (*Order, error) {
	params := []interface{}{
		orderId,
	}

	// Validate parameters
	methodDef := map[string]interface{}{
		"parameters": []interface{}{
			map[string]interface{}{
				"name": "orderId",
				"type": map[string]interface{}{"builtIn": "string"},
			},
		},
	}
	expectedParams, _ := methodDef["parameters"].([]interface{})
	for i, paramValue := range params {
		paramDef, _ := expectedParams[i].(map[string]interface{})
		paramType, _ := paramDef["type"].(map[string]interface{})
		// Convert param to interface{} for validation
		var paramInterface interface{}
		paramJSON, _ := json.Marshal(paramValue)
		json.Unmarshal(paramJSON, &paramInterface)
		if err := ValidateType(paramInterface, paramType, ALL_STRUCTS, ALL_ENUMS, false); err != nil {
			paramName, _ := paramDef["name"].(string)
			var zero *Order
			return zero, fmt.Errorf("parameter %d (%s) validation failed: %w", i, paramName, err)
		}
	}

	methodName := "OrderService.getOrder"
	response, err := c.transport.Call(methodName, params)
	if err != nil {
		var zero *Order
		return zero, err
	}

	result, ok := response["result"]
	if !ok {
		var zero *Order
		return zero, nil
	}

	// Validate result
	returnType := map[string]interface{}{"userDefined": "Order"}
	returnOptional := true
	var resultInterface interface{}
	resultJSON, _ := json.Marshal(result)
	json.Unmarshal(resultJSON, &resultInterface)
	if err := ValidateType(resultInterface, returnType, ALL_STRUCTS, ALL_ENUMS, returnOptional); err != nil {
		var zero *Order
		return zero, fmt.Errorf("response validation failed: %w", err)
	}

	var typedResult *Order
	if err := json.Unmarshal(resultJSON, &typedResult); err != nil {
		var zero *Order
		return zero, fmt.Errorf("failed to unmarshal result: %w", err)
	}
	return typedResult, nil
}

