// Generated by barrister - do not edit

package checkout.checkout;

public class CartServiceImpl implements CartService {
    @Override
    public Cart addToCart(AddToCartRequest request) {
        return null;
    }

    @Override
    public Cart getCart(String cartId) {
        return null;
    }

    @Override
    public boolean clearCart(String cartId) {
        return true;
    }

}
