// Generated by barrister - do not edit

package checkout.checkout;

public interface CartService {
    public Cart addToCart(AddToCartRequest request);

    public Cart getCart(String cartId);

    public boolean clearCart(String cartId);

}
