// Generated by barrister - do not edit

package checkout.checkout;

public interface CatalogService {
    public java.util.List<Product> listProducts();

    public Product getProduct(String productId);

}
