// Generated by barrister - do not edit

package checkout.checkout;

public class CatalogServiceImpl implements CatalogService {
    @Override
    public java.util.List<Product> listProducts() {
        return new java.util.ArrayList<Product>();
    }

    @Override
    public Product getProduct(String productId) {
        return null;
    }

}
