// Generated by barrister - do not edit

package checkout.checkout;

import com.bitmechanic.barrister2.*;
import com.fasterxml.jackson.core.type.TypeReference;
public class CatalogServiceClient implements CatalogService {
    private final Transport transport;
    private final JsonParser jsonParser;

    public CatalogServiceClient(Transport transport, JsonParser jsonParser) {
        this.transport = transport;
        this.jsonParser = jsonParser;
    }

    @Override
    public java.util.List<Product> listProducts() {
        try {
            String method = "CatalogService.listProducts";
            Object[] params = new Object[] {  };

            Request rpcRequest = new Request(method, params, java.util.UUID.randomUUID().toString());
            Response response = transport.call(rpcRequest);

            if (response.getResult() == null) {
                throw new RPCError(-32603, "Internal error", "Missing result in response");
            }

            String resultJson = jsonParser.toJson(response.getResult());
            com.fasterxml.jackson.core.type.TypeReference<java.util.List<Product>> typeRef = new com.fasterxml.jackson.core.type.TypeReference<java.util.List<Product>>() {};
            return jsonParser.fromJson(resultJson, typeRef.getType());
        } catch (Exception e) {
            if (e instanceof RPCError) {
                throw (RPCError) e;
            }
            throw new RPCError(-32603, "Internal error", e.getMessage());
        }
    }

    @Override
    public Product getProduct(String productId) {
        try {
            String method = "CatalogService.getProduct";
            Object[] params = new Object[] { productId };

            Request rpcRequest = new Request(method, params, java.util.UUID.randomUUID().toString());
            Response response = transport.call(rpcRequest);

            if (response.getResult() == null) {
                return null;
            }

            String resultJson = jsonParser.toJson(response.getResult());
            com.fasterxml.jackson.core.type.TypeReference<Product> typeRef = new com.fasterxml.jackson.core.type.TypeReference<Product>() {};
            return jsonParser.fromJson(resultJson, typeRef.getType());
        } catch (Exception e) {
            if (e instanceof RPCError) {
                throw (RPCError) e;
            }
            throw new RPCError(-32603, "Internal error", e.getMessage());
        }
    }

}
