// Generated by barrister - do not edit

package checkout.checkout;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;
import java.util.List;

// IDL-specific type definitions for namespace: checkout
public final class checkoutIdl {
    public static final java.util.Map<String, java.util.Map<String, Object>> ALL_STRUCTS;
    public static final java.util.Map<String, java.util.Map<String, Object>> ALL_ENUMS;

    static {
        java.util.Map<String, java.util.Map<String, Object>> structs = new java.util.HashMap<>();
        java.util.Map<String, java.util.Map<String, Object>> enums = new java.util.HashMap<>();

        {
            java.util.Map<String, Object> def = new java.util.HashMap<>();
            java.util.List<java.util.Map<String, Object>> fields = new java.util.ArrayList<>();
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "productId");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "name");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "description");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "price");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "float");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "stock");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "int");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "imageUrl");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                f.put("optional", true);
                fields.add(f);
            }
            def.put("fields", fields);
            structs.put("Product", def);
        }
        {
            java.util.Map<String, Object> def = new java.util.HashMap<>();
            java.util.List<java.util.Map<String, Object>> fields = new java.util.ArrayList<>();
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "productId");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "quantity");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "int");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "price");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "float");
                f.put("type", typeDef);
                fields.add(f);
            }
            def.put("fields", fields);
            structs.put("CartItem", def);
        }
        {
            java.util.Map<String, Object> def = new java.util.HashMap<>();
            java.util.List<java.util.Map<String, Object>> fields = new java.util.ArrayList<>();
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "cartId");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "items");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                java.util.Map<String, Object> inner = new java.util.HashMap<>();
                typeDef.put("userDefined", "CartItem");
                typeDef.put("array", inner);
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "subtotal");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "float");
                f.put("type", typeDef);
                fields.add(f);
            }
            def.put("fields", fields);
            structs.put("Cart", def);
        }
        {
            java.util.Map<String, Object> def = new java.util.HashMap<>();
            java.util.List<java.util.Map<String, Object>> fields = new java.util.ArrayList<>();
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "street");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "city");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "state");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "zipCode");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "country");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            def.put("fields", fields);
            structs.put("Address", def);
        }
        {
            java.util.Map<String, Object> def = new java.util.HashMap<>();
            java.util.List<java.util.Map<String, Object>> fields = new java.util.ArrayList<>();
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "orderId");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "cart");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("userDefined", "Cart");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "shippingAddress");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("userDefined", "Address");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "paymentMethod");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("userDefined", "PaymentMethod");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "status");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("userDefined", "OrderStatus");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "total");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "float");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "createdAt");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "int");
                f.put("type", typeDef);
                fields.add(f);
            }
            def.put("fields", fields);
            structs.put("Order", def);
        }
        {
            java.util.Map<String, Object> def = new java.util.HashMap<>();
            java.util.List<java.util.Map<String, Object>> fields = new java.util.ArrayList<>();
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "cartId");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                f.put("optional", true);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "productId");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "quantity");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "int");
                f.put("type", typeDef);
                fields.add(f);
            }
            def.put("fields", fields);
            structs.put("AddToCartRequest", def);
        }
        {
            java.util.Map<String, Object> def = new java.util.HashMap<>();
            java.util.List<java.util.Map<String, Object>> fields = new java.util.ArrayList<>();
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "cartId");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "shippingAddress");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("userDefined", "Address");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "paymentMethod");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("userDefined", "PaymentMethod");
                f.put("type", typeDef);
                fields.add(f);
            }
            def.put("fields", fields);
            structs.put("CreateOrderRequest", def);
        }
        {
            java.util.Map<String, Object> def = new java.util.HashMap<>();
            java.util.List<java.util.Map<String, Object>> fields = new java.util.ArrayList<>();
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "orderId");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                fields.add(f);
            }
            {
                java.util.Map<String, Object> f = new java.util.HashMap<>();
                f.put("name", "message");
                java.util.Map<String, Object> typeDef = new java.util.HashMap<>();
                typeDef.put("builtIn", "string");
                f.put("type", typeDef);
                f.put("optional", true);
                fields.add(f);
            }
            def.put("fields", fields);
            structs.put("CheckoutResponse", def);
        }
        {
            java.util.Map<String, Object> ed = new java.util.HashMap<>();
            java.util.List<java.util.Map<String, Object>> values = new java.util.ArrayList<>();
            {
                java.util.Map<String, Object> ev = new java.util.HashMap<>();
                ev.put("name", "pending");
                values.add(ev);
            }
            {
                java.util.Map<String, Object> ev = new java.util.HashMap<>();
                ev.put("name", "paid");
                values.add(ev);
            }
            {
                java.util.Map<String, Object> ev = new java.util.HashMap<>();
                ev.put("name", "shipped");
                values.add(ev);
            }
            {
                java.util.Map<String, Object> ev = new java.util.HashMap<>();
                ev.put("name", "delivered");
                values.add(ev);
            }
            {
                java.util.Map<String, Object> ev = new java.util.HashMap<>();
                ev.put("name", "cancelled");
                values.add(ev);
            }
            ed.put("values", values);
            enums.put("OrderStatus", ed);
        }
        {
            java.util.Map<String, Object> ed = new java.util.HashMap<>();
            java.util.List<java.util.Map<String, Object>> values = new java.util.ArrayList<>();
            {
                java.util.Map<String, Object> ev = new java.util.HashMap<>();
                ev.put("name", "credit_card");
                values.add(ev);
            }
            {
                java.util.Map<String, Object> ev = new java.util.HashMap<>();
                ev.put("name", "debit_card");
                values.add(ev);
            }
            {
                java.util.Map<String, Object> ev = new java.util.HashMap<>();
                ev.put("name", "paypal");
                values.add(ev);
            }
            {
                java.util.Map<String, Object> ev = new java.util.HashMap<>();
                ev.put("name", "apple_pay");
                values.add(ev);
            }
            ed.put("values", values);
            enums.put("PaymentMethod", ed);
        }
        ALL_STRUCTS = java.util.Collections.unmodifiableMap(structs);
        ALL_ENUMS = java.util.Collections.unmodifiableMap(enums);
    }
}
