// Generated by barrister - do not edit

package checkout.checkout;

import com.fasterxml.jackson.annotation.JsonProperty;
public class CheckoutResponse {
    @JsonProperty("orderId")
    private String orderId;

    @JsonProperty("message")
    private String message;

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

}
