// Generated by barrister - do not edit

package checkout.checkout;

import com.fasterxml.jackson.annotation.JsonProperty;
public class CreateOrderRequest {
    @JsonProperty("cartId")
    private String cartId;

    @JsonProperty("shippingAddress")
    private Address shippingAddress;

    @JsonProperty("paymentMethod")
    private PaymentMethod paymentMethod;

    public String getCartId() {
        return cartId;
    }

    public void setCartId(String cartId) {
        this.cartId = cartId;
    }

    public Address getShippingAddress() {
        return shippingAddress;
    }

    public void setShippingAddress(Address shippingAddress) {
        this.shippingAddress = shippingAddress;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

}
