// Generated by barrister - do not edit

package checkout.checkout;

public interface OrderService {
    public CheckoutResponse createOrder(CreateOrderRequest request);

    public Order getOrder(String orderId);

}
