// Generated by barrister - do not edit

package checkout.checkout;

public class OrderServiceImpl implements OrderService {
    @Override
    public CheckoutResponse createOrder(CreateOrderRequest request) {
        // Return a valid checkout response to pass validation
        CheckoutResponse response = new CheckoutResponse();
        response.orderId = "order-1";
        response.status = "pending";
        return response;
    }

    @Override
    public Order getOrder(String orderId) {
        // Return a valid order to pass validation
        Order order = new Order();
        order.orderId = orderId;
        order.status = "pending";
        order.paymentMethod = "credit_card";
        order.shippingAddress = new Address();
        order.shippingAddress.street = "123 Test St";
        order.shippingAddress.city = "Test City";
        order.shippingAddress.state = "TS";
        order.shippingAddress.zipCode = "12345";
        order.shippingAddress.country = "USA";
        return order;
    }

}
